/*
 Highcharts JS v5.0.11 (2018-09-19)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(L){"object"===typeof module&&module.exports?module.exports=L:L(Highcharts)})(function(L){(function(a){var F=a.addEvent,r=a.Axis,A=a.Chart,D=a.css,G=a.dateFormat,E=a.defined,y=a.each,p=a.extend,x=a.noop,w=a.timeUnits,J=a.wrap;J(a.Series.prototype,"init",function(a){var l;a.apply(this,Array.prototype.slice.call(arguments,1));(l=this.xAxis)&&l.options.ordinal&&F(this,"updatedData",function(){delete l.ordinalIndex})});J(r.prototype,"getTimeTicks",function(a,e,b,c,v,g,m,f){var q=0,l,u,d={},k=
[],t=-Number.MAX_VALUE,H=this.options.tickPixelInterval;if(!this.options.ordinal&&!this.options.breaks||!g||3>g.length||void 0===b)return a.call(this,e,b,c,v);var B=g.length;for(l=0;l<B;l++){var h=l&&g[l-1]>c;g[l]<b&&(q=l);if(l===B-1||g[l+1]-g[l]>5*m||h){if(g[l]>t){for(u=a.call(this,e,g[q],g[l],v);u.length&&u[0]<=t;)u.shift();u.length&&(t=u[u.length-1]);k=k.concat(u)}q=l+1}if(h)break}a=u.info;if(f&&a.unitRange<=w.hour){l=k.length-1;for(q=1;q<l;q++)if(G("%d",k[q])!==G("%d",k[q-1])){d[k[q]]="day";var n=
!0}n&&(d[k[0]]="day");a.higherRanks=d}k.info=a;if(f&&E(H)){f=a=k.length;l=[];var z;for(n=[];f--;)q=this.translate(k[f]),z&&(n[f]=z-q),l[f]=z=q;n.sort();n=n[Math.floor(n.length/2)];n<.6*H&&(n=null);f=k[a-1]>c?a-1:a;for(z=void 0;f--;)q=l[f],c=Math.abs(z-q),z&&c<.8*H&&(null===n||c<.8*n)?(d[k[f]]&&!d[k[f+1]]?(c=f+1,z=q):c=f,k.splice(c,1)):z=q}return k});p(r.prototype,{beforeSetTickPositions:function(){var a=[],e=!1,b=this.getExtremes(),c=b.min,v=b.max,g,m=this.isXAxis&&!!this.options.breaks;b=this.options.ordinal;
var f=this.chart.options.chart.ignoreHiddenSeries;if(b||m){y(this.series,function(b,d){if(!(f&&!1===b.visible||!1===b.takeOrdinalPosition&&!m)&&(a=a.concat(b.processedXData),q=a.length,a.sort(function(d,f){return d-f}),q))for(d=q-1;d--;)a[d]===a[d+1]&&a.splice(d,1)});var q=a.length;if(2<q){var C=a[1]-a[0];for(g=q-1;g--&&!e;)a[g+1]-a[g]!==C&&(e=!0);!this.options.keepOrdinalPadding&&(a[0]-c>C||v-a[a.length-1]>C)&&(e=!0)}e?(this.ordinalPositions=a,C=this.ordinal2lin(Math.max(c,a[0]),!0),g=Math.max(this.ordinal2lin(Math.min(v,
a[a.length-1]),!0),1),this.ordinalSlope=v=(v-c)/(g-C),this.ordinalOffset=c-C*v):this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0}this.isOrdinal=b&&e;this.groupIntervalFactor=null},val2lin:function(a,e){var b=this.ordinalPositions,c;if(b){var l=b.length;for(c=l;c--;)if(b[c]===a){var g=c;break}for(c=l-1;c--;)if(a>b[c]||0===c){b=(a-b[c])/(b[c+1]-b[c]);g=c+b;break}c=e?g:this.ordinalSlope*(g||0)+this.ordinalOffset}else c=a;return c},lin2val:function(a,e){var b=this.ordinalPositions;if(b){var c=
this.ordinalSlope,l=this.ordinalOffset,g=b.length-1;if(e)if(0>a)a=b[0];else if(a>g)a=b[g];else{g=Math.floor(a);var m=a-g}else for(;g--;){var f=c*g+l;if(a>=f){c=c*(g+1)+l;m=(a-f)/(c-f);break}}return void 0!==m&&void 0!==b[g]?b[g]+(m?m*(b[g+1]-b[g]):0):a}return a},getExtendedPositions:function(){var a=this.chart,e=this.series[0].currentDataGrouping,b=this.ordinalIndex,c=e?e.count+e.unitName:"raw",v=this.getExtremes(),g;b||(b=this.ordinalIndex={});if(!b[c]){var m={series:[],chart:a,getExtremes:function(){return{min:v.dataMin,
max:v.dataMax}},options:{ordinal:!0},val2lin:r.prototype.val2lin,ordinal2lin:r.prototype.ordinal2lin};y(this.series,function(f){g={xAxis:m,xData:f.xData,chart:a,destroyGroupedData:x};g.options={dataGrouping:e?{enabled:!0,forced:!0,approximation:"open",units:[[e.unitName,[e.count]]]}:{enabled:!1}};f.processData.apply(g);m.series.push(g)});this.beforeSetTickPositions.apply(m);b[c]=m.ordinalPositions}return b[c]},getGroupIntervalFactor:function(a,e,b){b=b.processedXData;var c=b.length,l=[];var g=this.groupIntervalFactor;
if(!g){for(g=0;g<c-1;g++)l[g]=b[g+1]-b[g];l.sort(function(a,f){return a-f});l=l[Math.floor(c/2)];a=Math.max(a,b[0]);e=Math.min(e,b[c-1]);this.groupIntervalFactor=g=c*l/(e-a)}return g},postProcessTickInterval:function(a){var e=this.ordinalSlope;return e?this.options.breaks?this.closestPointRange:a/(e/this.closestPointRange):a}});r.prototype.ordinal2lin=r.prototype.val2lin;J(A.prototype,"pan",function(a,e){var b=this.xAxis[0],c=e.chartX,l=!1;if(b.options.ordinal&&b.series.length){var g=this.mouseDownX,
m=b.getExtremes(),f=m.dataMax,q=m.min,C=m.max,u=this.hoverPoints,d=b.closestPointRange;g=(g-c)/(b.translationSlope*(b.ordinalSlope||d));var k={ordinalPositions:b.getExtendedPositions()};d=b.lin2val;var t=b.val2lin;if(!k.ordinalPositions)l=!0;else if(1<Math.abs(g)){u&&y(u,function(d){d.setState()});if(0>g){u=k;var H=b.ordinalPositions?b:k}else u=b.ordinalPositions?b:k,H=k;k=H.ordinalPositions;f>k[k.length-1]&&k.push(f);this.fixedRange=C-q;g=b.toFixedRange(null,null,d.apply(u,[t.apply(u,[q,!0])+g,!0]),
d.apply(H,[t.apply(H,[C,!0])+g,!0]));g.min>=Math.min(m.dataMin,q)&&g.max<=Math.max(f,C)&&b.setExtremes(g.min,g.max,!0,!1,{trigger:"pan"});this.mouseDownX=c;D(this.container,{cursor:"move"})}}else l=!0;l&&a.apply(this,Array.prototype.slice.call(arguments,1))})})(L);(function(a){function F(){return Array.prototype.slice.call(arguments,1)}function r(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))}var A=a.pick,D=a.wrap,G=a.each,E=a.extend,y=a.isArray,
p=a.fireEvent,x=a.Axis,w=a.Series;E(x.prototype,{isInBreak:function(a,l){var e=a.repeat||Infinity,b=a.from,c=a.to-a.from;e=l>=b?(l-b)%e:e-(b-l)%e;return a.inclusive?e<=c:e<c&&0!==e},isInAnyBreak:function(a,l){var e=this.options.breaks,b=e&&e.length,c;if(b){for(;b--;)if(this.isInBreak(e[b],a)){var v=!0;c||(c=A(e[b].showPoints,this.isXAxis?!1:!0))}var g=v&&l?v&&!c:v}return g}});D(x.prototype,"setTickPositions",function(a){a.apply(this,Array.prototype.slice.call(arguments,1));if(this.options.breaks){var l=
this.tickPositions,e=this.tickPositions.info,b=[],c;for(c=0;c<l.length;c++)this.isInAnyBreak(l[c])||b.push(l[c]);this.tickPositions=b;this.tickPositions.info=e}});D(x.prototype,"init",function(a,l,e){var b=this;e.breaks&&e.breaks.length&&(e.ordinal=!1);a.call(this,l,e);a=this.options.breaks;b.isBroken=y(a)&&!!a.length;b.isBroken&&(b.val2lin=function(a){var c=a,g;for(g=0;g<b.breakArray.length;g++){var e=b.breakArray[g];if(e.to<=a)c-=e.len;else if(e.from>=a)break;else if(b.isInBreak(e,a)){c-=a-e.from;
break}}return c},b.lin2val=function(a){var c;for(c=0;c<b.breakArray.length;c++){var e=b.breakArray[c];if(e.from>=a)break;else e.to<a?a+=e.len:b.isInBreak(e,a)&&(a+=e.len)}return a},b.setExtremes=function(a,b,e,l,f){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(b);)b-=this.closestPointRange;x.prototype.setExtremes.call(this,a,b,e,l,f)},b.setAxisTranslation=function(a){x.prototype.setAxisTranslation.call(this,a);a=b.options.breaks;var c=[],e=[],l=0,f,q=b.userMin||b.min,
C=b.userMax||b.max,u=A(b.pointRangePadding,0),d;G(a,function(d){f=d.repeat||Infinity;b.isInBreak(d,q)&&(q+=d.to%f-q%f);b.isInBreak(d,C)&&(C-=C%f-d.from%f)});G(a,function(a){t=a.from;for(f=a.repeat||Infinity;t-f>q;)t-=f;for(;t<q;)t+=f;for(d=t;d<C;d+=f)c.push({value:d,move:"in"}),c.push({value:d+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(d,a){return d.value===a.value?("in"===d.move?0:1)-("in"===a.move?0:1):d.value-a.value});var k=0;var t=q;G(c,function(d){k+="in"===d.move?1:-1;1===
k&&"in"===d.move&&(t=d.value);0===k&&(e.push({from:t,to:d.value,len:d.value-t-(d.size||0)}),l+=d.value-t-(d.size||0))});b.breakArray=e;b.unitLength=C-q-l+u;p(b,"afterBreaks");b.options.staticScale?b.transA=b.options.staticScale:b.unitLength&&(b.transA*=(C-b.min+u)/b.unitLength);u&&(b.minPixelPadding=b.transA*b.minPointOffset);b.min=q;b.max=C})});D(w.prototype,"generatePoints",function(a){a.apply(this,F(arguments));var l=this.xAxis,e=this.yAxis,b=this.points,c=b.length,v=this.options.connectNulls;
if(l&&e&&(l.options.breaks||e.options.breaks))for(;c--;){var g=b[c];var m=null===g.y&&!1===v;m||!l.isInAnyBreak(g.x,!0)&&!e.isInAnyBreak(g.y,!0)||(b.splice(c,1),this.data[c]&&this.data[c].destroyElements())}});a.Series.prototype.drawBreaks=function(a,l){var e=this,b=e.points,c,v,g,m;a&&G(l,function(f){c=a.breakArray||[];v=a.isXAxis?a.min:A(e.options.threshold,a.min);G(b,function(b){m=A(b["stack"+f.toUpperCase()],b[f]);G(c,function(f){g=!1;if(v<f.from&&m>f.to||v>f.from&&m<f.from)g="pointBreak";else if(v<
f.from&&m>f.from&&m<f.to||v>f.from&&m>f.to&&m<f.from)g="pointInBreak";g&&p(a,g,{point:b,brk:f})})})})};a.Series.prototype.gappedPath=function(){var a=this.options.gapSize,l=this.points.slice(),e=l.length-1;if(a&&0<e)for(;e--;)l[e+1].x-l[e].x>this.closestPointRange*a&&l.splice(e+1,0,{isNull:!0});return this.getGraphPath(l)};D(a.seriesTypes.column.prototype,"drawPoints",r);D(a.Series.prototype,"drawPoints",r)})(L);(function(a){var F=a.arrayMax,r=a.arrayMin,A=a.Axis,D=a.defaultPlotOptions,G=a.defined,
E=a.each,y=a.extend,p=a.format,x=a.isNumber,w=a.merge,J=a.pick,l=a.Point,e=a.Tooltip,b=a.wrap,c=a.Series.prototype,v=c.processData,g=c.generatePoints,m=c.destroy,f={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y",
"%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},q={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},C=a.defaultDataGroupingUnits=[["millisecond",
[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],u={sum:function(d){var a=d.length;if(!a&&d.hasNulls)var f=null;else if(a)for(f=0;a--;)f+=d[a];return f},average:function(d){var a=d.length;d=u.sum(d);x(d)&&a&&(d/=a);return d},averages:function(){var d=[];E(arguments,function(a){d.push(u.average(a))});return d},open:function(d){return d.length?d[0]:d.hasNulls?null:void 0},high:function(d){return d.length?
F(d):d.hasNulls?null:void 0},low:function(d){return d.length?r(d):d.hasNulls?null:void 0},close:function(d){return d.length?d[d.length-1]:d.hasNulls?null:void 0},ohlc:function(d,a,f,b){d=u.open(d);a=u.high(a);f=u.low(f);b=u.close(b);if(x(d)||x(a)||x(f)||x(b))return[d,a,f,b]},range:function(a,f){a=u.low(a);f=u.high(f);if(x(a)||x(f))return[a,f]}};c.groupData=function(a,k,b,c){var d=this.data,h=this.options.data,n=[],z=[],I=[],K=a.length,t=!!k,e=[];c="function"===typeof c?c:u[c]||q[this.type]&&u[q[this.type].approximation]||
u[f.approximation];var l=this.pointArrayMap,g=l&&l.length,H=0;var C=0;var m;g?E(l,function(){e.push([])}):e.push([]);var v=g||1;for(m=0;m<=K&&!(a[m]>=b[0]);m++);for(m;m<=K;m++){for(;void 0!==b[H+1]&&a[m]>=b[H+1]||m===K;){var p=b[H];this.dataGroupInfo={start:C,length:e[0].length};C=c.apply(this,e);void 0!==C&&(n.push(p),z.push(C),I.push(this.dataGroupInfo));C=m;for(p=0;p<v;p++)e[p].length=0,e[p].hasNulls=!1;H+=1;if(m===K)break}if(m===K)break;if(l){p=this.cropStart+m;var w=d&&d[p]||this.pointClass.prototype.applyOptions.apply({series:this},
[h[p]]);for(p=0;p<g;p++){var r=w[l[p]];x(r)?e[p].push(r):null===r&&(e[p].hasNulls=!0)}}else p=t?k[m]:null,x(p)?e[0].push(p):null===p&&(e[0].hasNulls=!0)}return[n,z,I]};c.processData=function(){var a=this.chart,f=this.options.dataGrouping,b=!1!==this.allowDG&&f&&J(f.enabled,a.options.isStock),q=this.visible||!a.options.chart.ignoreHiddenSeries,e;this.forceCrop=b;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==v.apply(this,arguments)&&b){this.destroyGroupedData();var h=this.processedXData,n=
this.processedYData,z=a.plotSizeX;a=this.xAxis;var I=a.options.ordinal,K=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(K){this.isDirty=e=!0;var M=a.getExtremes();b=M.min;M=M.max;I=I&&a.getGroupIntervalFactor(b,M,this)||1;z=K*(M-b)/z*I;K=a.getTimeTicks(a.normalizeTimeTickInterval(z,f.units||C),Math.min(b,h[0]),Math.max(M,h[h.length-1]),a.options.startOfWeek,h,this.closestPointRange);h=c.groupData.apply(this,[h,n,K,f.approximation]);n=h[0];I=h[1];if(f.smoothed){f=n.length-1;for(n[f]=
Math.min(n[f],M);f--&&0<f;)n[f]+=z/2;n[0]=Math.max(n[0],b)}this.currentDataGrouping=K.info;this.closestPointRange=K.info.totalRange;this.groupMap=h[2];G(n[0])&&n[0]<a.dataMin&&q&&(a.min===a.dataMin&&(a.min=n[0]),a.dataMin=n[0]);this.processedXData=n;this.processedYData=I}else this.currentDataGrouping=this.groupMap=null;this.hasGroupedData=e}};c.destroyGroupedData=function(){var a=this.groupedData;E(a||[],function(f,d){f&&(a[d]=f.destroy?f.destroy():null)});this.groupedData=null};c.generatePoints=
function(){g.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};b(l.prototype,"update",function(f){this.dataGroup?a.error(24):f.apply(this,[].slice.call(arguments,1))});b(e.prototype,"tooltipFooterHeaderFormatter",function(f,b,q){var d=b.series,k=d.tooltipOptions,h=d.options.dataGrouping,n=k.xDateFormat,z=d.xAxis,c=a.dateFormat;if(z&&"datetime"===z.options.type&&h&&x(b.key)){f=d.currentDataGrouping;h=h.dateTimeLabelFormats;if(f)if(z=h[f.unitName],1===f.count)n=
z[0];else{n=z[1];var K=z[2]}else!n&&h&&(n=this.getXDateFormat(b,k,z));n=c(n,b.key);K&&(n+=c(K,b.key+f.totalRange-1));return p(k[(q?"footer":"header")+"Format"],{point:y(b.point,{key:n}),series:d})}return f.call(this,b,q)});c.destroy=function(){for(var a=this.groupedData||[],f=a.length;f--;)a[f]&&a[f].destroy();m.apply(this)};b(c,"setOptions",function(a,b){var d=a.call(this,b),k=this.type,c=this.chart.options.plotOptions,h=D[k].dataGrouping;q[k]&&(h||(h=w(f,q[k])),d.dataGrouping=w(h,c.series&&c.series.dataGrouping,
c[k].dataGrouping,b.dataGrouping));this.chart.options.isStock&&(this.requireSorting=!0);return d});b(A.prototype,"setScale",function(a){a.call(this);E(this.series,function(a){a.hasProcessed=!1})});A.prototype.getGroupPixelWidth=function(){var a=this.series,f=a.length,b,q=0,c=!1,h;for(b=f;b--;)(h=a[b].options.dataGrouping)&&(q=Math.max(q,h.groupPixelWidth));for(b=f;b--;)(h=a[b].options.dataGrouping)&&a[b].hasProcessed&&(f=(a[b].processedXData||a[b].data).length,a[b].groupPixelWidth||f>this.chart.plotSizeX/
q||f&&h.forced)&&(c=!0);return c?q:0};A.prototype.setDataGrouping=function(a,f){var d;f=J(f,!0);a||(a={forced:!1,units:null});if(this instanceof A)for(d=this.series.length;d--;)this.series[d].update({dataGrouping:a},!1);else E(this.chart.options.series,function(f){f.dataGrouping=a},!1);f&&this.chart.redraw()}})(L);(function(a){var F=a.each,r=a.Point,A=a.seriesType,D=a.seriesTypes;A("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,r){var y=D.column.prototype.pointAttribs.call(this,a,r),p=this.options;delete y.fill;!a.options.color&&p.upColor&&a.open<a.close&&(y.stroke=p.upColor);return y},translate:function(){var a=this,r=a.yAxis,y=!!a.modifyValue,
p=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];D.column.prototype.translate.apply(a);F(a.points,function(x){F([x.open,x.high,x.low,x.close,x.low],function(w,E){null!==w&&(y&&(w=a.modifyValue(w)),x[p[E]]=r.toPixels(w,!0))});x.tooltipPos[1]=x.plotHigh+r.pos-a.chart.plotTop})},drawPoints:function(){var a=this,r=a.chart;F(a.points,function(y){var p=y.graphic,x=!p;if(void 0!==y.plotY){p||(y.graphic=p=r.renderer.path().add(a.group));p.attr(a.pointAttribs(y,y.selected&&"select"));var w=p.strokeWidth()%
2/2;var E=Math.round(y.plotX)-w;var l=Math.round(y.shapeArgs.width/2);var e=["M",E,Math.round(y.yBottom),"L",E,Math.round(y.plotHigh)];if(null!==y.open){var b=Math.round(y.plotOpen)+w;e.push("M",E,b,"L",E-l,b)}null!==y.close&&(b=Math.round(y.plotClose)+w,e.push("M",E,b,"L",E+l,b));p[x?"attr":"animate"]({d:e}).addClass(y.getClassName(),!0)}})},animate:null},{getClassName:function(){return r.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(L);
(function(a){var F=a.defaultPlotOptions,r=a.each,A=a.merge,D=a.seriesType,G=a.seriesTypes;D("candlestick","ohlc",A(F.column,{states:{hover:{lineWidth:2}},tooltip:F.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(a,r){var p=G.column.prototype.pointAttribs.call(this,a,r),x=this.options,w=a.open<a.close,y=x.lineColor||this.color;p["stroke-width"]=x.lineWidth;p.fill=a.options.color||(w?x.upColor||this.color:this.color);p.stroke=
a.lineColor||(w?x.upLineColor||y:y);r&&(x=x.states[r],p.fill=x.color||p.fill,p.stroke=x.lineColor||p.stroke,p["stroke-width"]=x.lineWidth||p["stroke-width"]);return p},drawPoints:function(){var a=this,y=a.chart;r(a.points,function(p){var r=p.graphic,w=!r;if(void 0!==p.plotY){r||(p.graphic=r=y.renderer.path().add(a.group));r.attr(a.pointAttribs(p,p.selected&&"select")).shadow(a.options.shadow);var A=r.strokeWidth()%2/2;var l=Math.round(p.plotX)-A;var e=p.plotOpen;var b=p.plotClose;var c=Math.min(e,
b);e=Math.max(e,b);var v=Math.round(p.shapeArgs.width/2);b=Math.round(c)!==Math.round(p.plotHigh);var g=e!==p.yBottom;c=Math.round(c)+A;e=Math.round(e)+A;A=[];A.push("M",l-v,e,"L",l-v,c,"L",l+v,c,"L",l+v,e,"Z","M",l,c,"L",l,b?Math.round(p.plotHigh):c,"M",l,e,"L",l,g?Math.round(p.yBottom):e);r[w?"attr":"animate"]({d:A}).addClass(p.getClassName(),!0)}})}})})(L);(function(a){var F=a.addEvent,r=a.each,A=a.merge,D=a.noop,G=a.Renderer,E=a.seriesType,y=a.seriesTypes,p=a.TrackerMixin,x=a.VMLRenderer,w=a.SVGRenderer.prototype.symbols,
J=a.stableSort;E("flags","column",{pointRange:0,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,pointAttribs:function(a,e){var b=this.options,c=a&&a.color||this.color,l=
b.lineColor,g=a&&a.lineWidth,m=a&&a.fillColor||b.fillColor;e&&(m=b.states[e].fillColor,l=b.states[e].lineColor,g=b.states[e].lineWidth);return{fill:m||c,stroke:l||c,"stroke-width":g||b.lineWidth||0}},translate:function(){y.column.prototype.translate.apply(this);var a=this.options,e=this.chart,b=this.points,c=b.length-1,p,g=a.onSeries;var m=g&&e.get(g);a=a.onKey||"y";g=m&&m.options.step;var f=m&&m.points,q=f&&f.length,C=this.xAxis,u=this.yAxis,d=C.getExtremes(),k=0,t;if(m&&m.visible&&q){k=(m.pointXOffset||
0)+(m.barW||0)/2;m=m.currentDataGrouping;var H=f[q-1].x+(m?m.totalRange:0);J(b,function(a,f){return a.x-f.x});for(a="plot"+a[0].toUpperCase()+a.substr(1);q--&&b[c];){m=b[c];var B=f[q];if(B.x<=m.x&&void 0!==B[a]&&(m.x<=H&&(m.plotY=B[a],B.x<m.x&&!g&&(t=f[q+1])&&void 0!==t[a]&&(m.plotY+=(m.x-B.x)/(t.x-B.x)*(t[a]-B[a]))),c--,q++,0>c))break}}r(b,function(a,f){void 0===a.plotY&&(a.x>=d.min&&a.x<=d.max?a.plotY=e.chartHeight-C.bottom-(C.opposite?C.height:0)+C.offset-u.top:a.shapeArgs={});a.plotX+=k;if((p=
b[f-1])&&p.plotX===a.plotX){void 0===p.stackIndex&&(p.stackIndex=0);var h=p.stackIndex+1}a.stackIndex=h})},drawPoints:function(){var l=this.points,e=this.chart,b=e.renderer,c=this.options,p=c.y,g,m=this.yAxis;for(g=l.length;g--;){var f=l[g];var q=f.plotX>this.xAxis.len;var C=f.plotX;var u=f.stackIndex;var d=f.options.shape||c.shape;var k=f.plotY;void 0!==k&&(k=f.plotY+p-(void 0!==u&&u*c.stackDistance));var t=u?void 0:f.plotX;var H=u?void 0:f.plotY;u=f.graphic;void 0!==k&&0<=C&&!q?(u||(u=f.graphic=
b.label("",null,null,d,null,null,c.useHTML).attr(this.pointAttribs(f)).css(A(c.style,f.style)).attr({align:"flag"===d?"left":"center",width:c.width,height:c.height,"text-align":c.textAlign}).addClass("highcharts-point").add(this.markerGroup),f.graphic.div&&(f.graphic.div.point=f),u.shadow(c.shadow)),0<C&&(C-=u.strokeWidth()%2),u.attr({text:f.options.title||c.title||"A",x:C,y:k,anchorX:t,anchorY:H}),f.tooltipPos=e.inverted?[m.len+m.pos-e.plotLeft-k,this.xAxis.len-C]:[C,k+m.pos-e.plotTop]):u&&(f.graphic=
u.destroy())}c.useHTML&&a.wrap(this.markerGroup,"on",function(f){return a.SVGElement.prototype.on.apply(f.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;p.drawTrackerPoint.apply(this);r(a,function(e){var b=e.graphic;b&&F(b.element,"mouseover",function(){0<e.stackIndex&&!e.raised&&(e._y=b.y,b.attr({y:e._y-8}),e.raised=!0);r(a,function(a){a!==e&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:D,buildKDTree:D,
setClip:D});w.flag=function(a,e,b,c,p){return["M",p&&p.anchorX||a,p&&p.anchorY||e,"L",a,e+c,a,e,a+b,e,a+b,e+c,a,e+c,"Z"]};r(["circle","square"],function(a){w[a+"pin"]=function(e,b,c,l,g){var m=g&&g.anchorX;g=g&&g.anchorY;"circle"===a&&l>c&&(e-=Math.round((l-c)/2),c=l);e=w[a](e,b,c,l);m&&g&&e.push("M",m,b>g?b:b+l,"L",m,g);return e}});G===x&&r(["flag","circlepin","squarepin"],function(a){x.prototype.symbols[a]=w[a]})})(L);(function(a){function F(a,b,c){this.init(a,b,c)}var r=a.addEvent,A=a.Axis,D=a.correctFloat,
G=a.defaultOptions,E=a.defined,y=a.destroyObjectProperties,p=a.doc,x=a.each,w=a.fireEvent,J=a.hasTouch,l=a.isTouchDevice,e=a.merge,b=a.pick,c=a.removeEvent,v=a.wrap,g,m={height:l?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:a.svg&&!l,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",
trackBorderColor:"#f2f2f2",trackBorderWidth:1};G.scrollbar=e(!0,m,G.scrollbar);a.swapXY=g=function(a,b){var f,q=a.length;if(b)for(f=0;f<q;f+=3){var d=a[f+1];a[f+1]=a[f+2];a[f+2]=d}return a};F.prototype={init:function(a,q,c){this.scrollbarButtons=[];this.renderer=a;this.userOptions=q;this.options=e(m,q);this.chart=c;this.size=b(this.options.size,this.options.height);q.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,b=this.options,c=this.size,e;this.group=
e=a.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||0,height:c,width:c}).add(e);this.track.attr({fill:b.trackBackgroundColor,stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(e);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:c,width:c,
r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(g(["M",-3,c/4,"L",-3,2*c/3,"M",0,c/4,"L",0,2*c/3,"M",3,c/4,"L",3,2*c/3],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth});this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1});this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,b,c,e){var f=this.options.vertical,q=0,t=this.rendered?"animate":"attr";this.x=a;this.y=b+this.trackBorderWidth;this.width=c;this.xOffset=this.height=e;this.yOffset=q;f?(this.width=this.yOffset=c=q=this.size,this.xOffset=b=0,this.barWidth=e-2*c,this.x=a+=this.options.margin):(this.height=this.xOffset=e=b=this.size,this.barWidth=c-2*e,this.y+=this.options.margin);this.group[t]({translateX:a,
translateY:this.y});this.track[t]({width:c,height:e});this.scrollbarButtons[1][t]({translateX:f?0:c-b,translateY:f?e-q:0})},drawScrollbarButton:function(a){var f=this.renderer,b=this.scrollbarButtons,c=this.options,d=this.size;var e=f.g().add(this.group);b.push(e);e=f.rect().addClass("highcharts-scrollbar-button").add(e);e.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});e.attr(e.crisp({x:-.5,y:-.5,width:d+1,height:d+1,r:c.buttonBorderRadius},e.strokeWidth()));
e=f.path(g(["M",d/2+(a?-1:1),d/2-3,"L",d/2+(a?-1:1),d/2+3,"L",d/2+(a?2:-2),d/2],c.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a]);e.attr({fill:c.buttonArrowColor})},setRange:function(a,b){var f=this.options,c=f.vertical,d=f.minWidth,e=this.barWidth,q,g=this.rendered&&!this.hasDragged?"animate":"attr";if(E(e)){a=Math.max(a,0);var B=Math.ceil(e*a);this.calculatedWidth=q=D(e*Math.min(b,1)-B);q<d&&(B=(e-d+q)*a,q=d);d=Math.floor(B+this.xOffset+this.yOffset);e=q/2-.5;this.from=a;this.to=b;c?
(this.scrollbarGroup[g]({translateY:d}),this.scrollbar[g]({height:q}),this.scrollbarRifles[g]({translateY:e}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:d}),this.scrollbar[g]({width:q}),this.scrollbarRifles[g]({translateX:e}),this.scrollbarLeft=d,this.scrollbarTop=0);12>=q?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===f.showFull&&(0>=a&&1<=b?this.group.hide():this.group.show());this.rendered=!0}},initEvents:function(){var a=this;a.mouseMoveHandler=
function(b){var f=a.chart.pointer.normalize(b),c=a.options.vertical?"chartY":"chartX",d=a.initPositions;!a.grabbedCenter||b.touches&&0===b.touches[0][c]||(f=a.cursorToScrollbarPosition(f)[c],c=a[c],c=f-c,a.hasDragged=!0,a.updatePosition(d[0]+c,d[1]+c),a.hasDragged&&w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};a.mouseUpHandler=function(b){a.hasDragged&&w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=
a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(b){var f=D(a.to-a.from)*a.options.step;a.updatePosition(D(a.from-f),D(a.to-f));w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=function(b){var f=(a.to-a.from)*a.options.step;a.updatePosition(a.from+f,a.to+f);w(a,"changed",{from:a.from,
to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var f=a.chart.pointer.normalize(b),c=a.to-a.from,d=a.y+a.scrollbarTop,e=a.x+a.scrollbarLeft;a.options.vertical&&f.chartY>d||!a.options.vertical&&f.chartX>e?a.updatePosition(a.from+c,a.to+c):a.updatePosition(a.from-c,a.to-c);w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=this.options;b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/
(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=D(1-D(b-a)),b=1);0>a&&(b=D(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();this.init(this.chart.renderer,e(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,c=this.scrollbarGroup.element,e=this.mouseDownHandler,d=this.mouseMoveHandler,k=this.mouseUpHandler;a=[[b[a[0]].element,"click",this.buttonToMinClick],
[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[c,"mousedown",e],[p,"mousemove",d],[p,"mouseup",k]];J&&a.push([c,"touchstart",e],[p,"touchmove",d],[p,"touchend",k]);x(a,function(a){r.apply(null,a)});this._events=a},removeEvents:function(){x(this._events,function(a){c.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();x(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&
this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,y(a.scrollbarButtons))}};v(A.prototype,"init",function(a){var c=this;a.apply(c,Array.prototype.slice.call(arguments,1));c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=new F(c.chart.renderer,c.options.scrollbar,c.chart),r(c.scrollbar,"changed",function(a){var f=Math.min(b(c.options.min,c.min),c.min,c.dataMin),
d=Math.max(b(c.options.max,c.max),c.max,c.dataMax)-f;if(c.horiz&&!c.reversed||!c.horiz&&c.reversed){var e=f+d*this.to;f+=d*this.from}else e=f+d*(1-this.from),f+=d*(1-this.to);c.setExtremes(f,e,!0,!1,a)}))});v(A.prototype,"render",function(a){var c=Math.min(b(this.options.min,this.min),this.min,this.dataMin),f=Math.max(b(this.options.max,this.max),this.max,this.dataMax),e=this.scrollbar,d=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(e){this.horiz?(e.position(this.left,
this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:d+this.axisTitleMargin+this.offset),this.width,this.height),d=1):(e.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?d+this.axisTitleMargin+this.offset:0),this.top,this.width,this.height),d=0);if(!this.opposite&&!this.horiz||this.opposite&&this.horiz)this.chart.scrollbarsOffsets[d]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(c)||isNaN(f)||!E(this.min)||!E(this.max)?e.setRange(0,0):(d=
(this.min-c)/(f-c),c=(this.max-c)/(f-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?e.setRange(d,c):e.setRange(1-c,1-d))}});v(A.prototype,"getOffset",function(a){var b=this.horiz?2:1,c=this.scrollbar;a.apply(this,Array.prototype.slice.call(arguments,1));c&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=c.size+c.options.margin)});v(A.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,
1))});a.Scrollbar=F})(L);(function(a){function F(a){this.init(a)}var r=a.addEvent,A=a.Axis,D=a.Chart,G=a.color,E=a.defaultOptions,y=a.defined,p=a.destroyObjectProperties,x=a.doc,w=a.each,J=a.erase,l=a.error,e=a.extend,b=a.grep,c=a.hasTouch,v=a.isNumber,g=a.isObject,m=a.merge,f=a.pick,q=a.removeEvent,C=a.Scrollbar,u=a.Series,d=a.seriesTypes,k=a.wrap,t=a.swapXY,H=[].concat(a.defaultDataGroupingUnits),B=function(a){var h=b(arguments,v);if(h.length)return Math[a].apply(0,h)};H[4]=["day",[1,2,3,4]];H[5]=
["week",[1,2,3]];d=void 0===d.areaspline?"line":"areaspline";e(E,{navigator:{height:40,margin:25,maskInside:!0,handles:{backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:G("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:d,color:"#335cad",fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:H},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",
lineColor:null,marker:{enabled:!1},pointRange:0,shadow:!1,threshold:null},xAxis:{className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});F.prototype={drawHandle:function(a,
b,d,c){this.handles[b][c](d?{translateX:Math.round(this.left+this.height/2-8),translateY:Math.round(this.top+parseInt(a,10)+.5)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-8)})},getHandlePath:function(a){return t(["M",-4.5,.5,"L",3.5,.5,"L",3.5,15.5,"L",-4.5,15.5,"L",-4.5,.5,"M",-1.5,4,"L",-1.5,12,"M",.5,4,"L",.5,12],a)},drawOutline:function(a,b,d,c){var h=this.navigatorOptions.maskInside,n=this.outline.strokeWidth(),f=n/2;n=n%2/2;var e=this.outlineHeight,
z=this.scrollbarHeight,I=this.size,k=this.left-z,g=this.top;d?(k-=f,d=g+b+n,b=g+a+n,a=["M",k+e,g-z-n,"L",k+e,d,"L",k,d,"L",k,b,"L",k+e,b,"L",k+e,g+I+z].concat(h?["M",k+e,d-f,"L",k+e,b+f]:[])):(a+=k+z-n,b+=k+z-n,g+=f,a=["M",k,g,"L",a,g,"L",a,g+e,"L",b,g+e,"L",b,g,"L",k+I+2*z,g].concat(h?["M",a-f,g,"L",b+f,g]:[]));this.outline[c]({d:a})},drawMasks:function(a,b,d,c){var h=this.left,n=this.top,f=this.height;if(d){var e=[h,h,h];var z=[n,n+a,n+b];var I=[f,f,f];var k=[a,b-a,this.size-b]}else e=[h,h+a,h+
b],z=[n,n,n],I=[a,b-a,this.size-b],k=[f,f,f];w(this.shades,function(a,b){a[c]({x:e[b],y:z[b],width:I[b],height:k[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,d=b.maskInside,c=a.chart,f=c.inverted,e=c.renderer,k;a.navigatorGroup=k=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();var g={cursor:f?"ns-resize":"ew-resize"};w([!d,d,!d],function(h,d){a.shades[d]=e.rect().addClass("highcharts-navigator-mask"+(1===d?"-inside":"-outside")).attr({fill:h?b.maskFill:"transparent"}).css(1===
d&&g).add(k)});a.outline=e.path().addClass("highcharts-navigator-outline").attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor}).add(k);w([0,1],function(h){a.handles[h]=e.path(a.getHandlePath(f)).attr({zIndex:7-h}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][h]).add(k);var d=b.handles;a.handles[h].attr({fill:d.backgroundColor,stroke:d.borderColor,"stroke-width":1}).css(g)})},update:function(a){this.destroy();m(!0,this.chart.options.navigator,this.options,
a);this.init(this.chart)},render:function(a,b,d,c){var h=this.chart,n=this.scrollbarHeight,e,z=this.xAxis;var k=z.fake?h.xAxis[0]:z;var g=this.navigatorEnabled,I,B=this.rendered;var t=h.inverted;var l=h.xAxis[0].minRange;if(!this.hasDragged||y(d)){if(!v(a)||!v(b))if(B)d=0,c=z.width;else return;this.left=f(z.left,h.plotLeft+n+(t?h.plotWidth:0));this.size=I=e=f(z.len,(t?h.plotHeight:h.plotWidth)-2*n);h=t?n:e+2*n;d=f(d,z.toPixels(a,!0));c=f(c,z.toPixels(b,!0));v(d)&&Infinity!==Math.abs(d)||(d=0,c=h);
a=z.toValue(d,!0);b=z.toValue(c,!0);if(Math.abs(b-a)<l)if(this.grabbedLeft)d=z.toPixels(b-l,!0);else if(this.grabbedRight)c=z.toPixels(a+l,!0);else return;this.zoomedMax=Math.min(Math.max(d,c,0),I);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(d,c),0),I);this.range=this.zoomedMax-this.zoomedMin;I=Math.round(this.zoomedMax);d=Math.round(this.zoomedMin);g&&(this.navigatorGroup.attr({visibility:"visible"}),B=B&&!this.hasDragged?"animate":"attr",this.drawMasks(d,
I,t,B),this.drawOutline(d,I,t,B),this.drawHandle(d,0,t,B),this.drawHandle(I,1,t,B));this.scrollbar&&(t?(t=this.top-n,k=this.left-n+(g?0:(k.titleOffset||0)+k.axisTitleMargin),n=e+2*n):(t=this.top+(g?this.height:-n),k=this.left-n),this.scrollbar.position(k,t,h,n),this.scrollbar.setRange(this.zoomedMin/e,this.zoomedMax/e));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,d=b.container,f=[],e,k;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=k=function(b){a.onMouseUp(b)};
f=a.getPartsEvents("mousedown");f.push(r(d,"mousemove",e),r(x,"mouseup",k));c&&(f.push(r(d,"touchmove",e),r(x,"touchend",k)),f.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=f;a.series&&a.series[0]&&f.push(r(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,d=[];w(["shades","handles"],function(h){w(b[h],function(c,n){d.push(r(c.element,a,function(a){b[h+"Mousedown"](a,n)}))})});return d},shadesMousedown:function(a,
b){a=this.chart.pointer.normalize(a);var d=this.chart,h=this.xAxis,c=this.zoomedMin,n=this.left,f=this.size,e=this.range,k=a.chartX;d.inverted&&(k=a.chartY,n=this.top);if(1===b)this.grabbedCenter=k,this.fixedWidth=e,this.dragOffset=k-c;else{n=k-n-e/2;if(0===b)n=Math.max(0,n);else if(2===b&&n+e>=f){n=f-e;var g=this.getUnionExtremes().dataMax}n!==c&&(this.fixedWidth=e,h=h.toFixedRange(n,n+e,null,g),d.xAxis[0].setExtremes(Math.min(h.min,h.max),Math.max(h.min,h.max),!0,null,{trigger:"navigator"}))}},
handlesMousedown:function(a,b){this.chart.pointer.normalize(a);var d=this.chart,h=d.xAxis[0],c=d.inverted&&!h.reversed||!d.inverted&&h.reversed;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=c?h.min:h.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=c?h.max:h.min);d.fixedRange=null},onMouseMove:function(a){var b=this,d=b.chart,h=b.left,c=b.navigatorSize,f=b.range,e=b.dragOffset,k=d.inverted;a.touches&&0===a.touches[0].pageX||(a=d.pointer.normalize(a),
d=a.chartX,k&&(h=b.top,d=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,d-h,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,d-h)):b.grabbedCenter&&(b.hasDragged=!0,d<e?d=e:d>c+e-f&&(d=c+e-f),b.render(0,0,d-e,d-e+f)),b.hasDragged&&b.scrollbar&&b.scrollbar.options.liveRedraw&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,d=this.xAxis,h=this.scrollbar,c=a.DOMEvent||a;if(this.hasDragged&&(!h||!h.hasDragged)||
"scrollbar"===a.trigger){if(this.zoomedMin===this.otherHandlePos)var f=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var e=this.fixedExtreme;this.zoomedMax===this.size&&(e=this.getUnionExtremes().dataMax);d=d.toFixedRange(this.zoomedMin,this.zoomedMax,f,e);y(d.min)&&b.xAxis[0].setExtremes(Math.min(d.min,d.max),Math.max(d.min,d.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:c})}"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=
this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(w(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&!1!==this.navigatorOptions.adaptToUpdatedData&&(w(a,function(a){q(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&q(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},
init:function(a){var b=a.options,d=b.navigator,c=d.enabled,h=b.scrollbar,e=h.enabled;b=c?d.height:0;var g=e?h.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=g;this.scrollbarEnabled=e;this.navigatorEnabled=c;this.navigatorOptions=d;this.scrollbarOptions=h;this.outlineHeight=b+g;this.opposite=f(d.opposite,!c&&a.inverted);var t=this;h=t.baseSeries;e=a.xAxis.length;var l=a.yAxis.length,p=h&&h[0]&&h[0].xAxis||a.xAxis[0];a.extraMargin={type:t.opposite?
"plotTop":"marginBottom",value:(c||!a.inverted?t.outlineHeight:0)+d.margin};a.inverted&&(a.extraMargin.type=t.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;t.navigatorEnabled?(t.xAxis=new A(a,m({breaks:p.options.breaks,ordinal:p.options.ordinal},d.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[g,0,-g,0],width:b}:{offsets:[0,-g,0,g],height:b})),
t.yAxis=new A(a,m(d.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:l,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),h||d.series.data?t.addBaseSeries():0===a.series.length&&k(a,"redraw",function(b,d){0<a.series.length&&!t.series&&(t.setBaseSeries(),a.redraw=b);b.call(a,d)}),t.renderElements(),t.addMouseEvents()):t.xAxis={translate:function(b,d){var c=a.xAxis[0],h=c.getExtremes(),e=c.len-2*g,f=B("min",c.options.min,h.dataMin);c=B("max",c.options.max,h.dataMax)-f;return d?b*c/e+f:e*(b-
f)/c},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:A.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=t.scrollbar=new C(a.renderer,m(a.options.scrollbar,{margin:t.navigatorEnabled?0:10,vertical:a.inverted}),a),r(t.scrollbar,"changed",function(b){var d=t.size,c=d*this.to;d*=this.from;t.hasDragged=t.scrollbar.hasDragged;t.render(0,0,d,c);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType)&&setTimeout(function(){t.onMouseUp(b)})}));
t.addBaseSeriesEvents();t.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],d=this.xAxis,c=d.options,h=b.options,e;a&&null===b.dataMin||(e={dataMin:f(c&&c.min,B("min",h.min,b.dataMin,d.dataMin,d.min)),dataMax:f(c&&c.max,B("max",h.max,b.dataMax,d.dataMax,d.max))});return e},setBaseSeries:function(a){var b=this.chart;a=a||b.options&&b.options.navigator.baseSeries||0;this.series&&(this.removeBaseSeriesEvents(),w(this.series,function(a){a.destroy()}));var d=this.baseSeries=[];w(b.series||
[],function(b,c){(b.options.showInNavigator||(c===a||b.options.id===a)&&!1!==b.options.showInNavigator)&&d.push(b)});this.xAxis&&!this.xAxis.fake&&this.addBaseSeries()},addBaseSeries:function(){var a=this,b=a.chart,d=a.series=[],c=a.baseSeries,e,f=a.navigatorOptions.series,k,g={enableMouseTracking:!1,index:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0};if(c)w(c,function(c,h){g.name="Navigator "+(h+1);e=c.options||
{};k=e.navigatorOptions||{};t=m(e,g,f,k);var n=k.data||f.data;a.hasNavigatorData=a.hasNavigatorData||!!n;t.data=n||e.data&&e.data.slice(0);c.navigatorSeries=b.initSeries(t);d.push(c.navigatorSeries)});else{var t=m(f,g);t.data=f.data;a.hasNavigatorData=!!t.data;d.push(b.initSeries(t))}this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&r(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);!1!==this.navigatorOptions.adaptToUpdatedData&&w(b,
function(b){b.xAxis&&r(b,"updatedData",this.updatedDataHandler);r(b,"remove",function(){this.navigatorSeries&&(J(a.series,this.navigatorSeries),this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),d=b.dataMin,c=b.dataMax;
b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,k=a.series&&a.series[0],g=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var t=d;var B=t+b}f&&(B=c,e||(t=Math.max(B-b,k&&k.xData?k.xData[0]:-Number.MAX_VALUE)));g&&(e||f)&&v(t)&&(this.min=this.userMin=t,this.max=this.userMax=B)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries;a.stickToMin=v(this.xAxis.min)&&this.xAxis.min<=this.xData[0];a.stickToMax=
Math.round(a.zoomedMax)>=Math.round(a.size);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){r(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)})},destroy:function(){this.removeEvents();this.xAxis&&(J(this.chart.xAxis,this.xAxis),J(this.chart.axes,this.xAxis));this.yAxis&&(J(this.chart.yAxis,this.yAxis),J(this.chart.axes,
this.yAxis));w(this.series||[],function(a){a.destroy&&a.destroy()});w("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);w([this.handles],function(a){p(a)},this)}};a.Navigator=F;k(A.prototype,"zoom",function(a,b,d){var c=this.chart,e=c.options,f=e.chart.zoomType,h=e.navigator;e=e.rangeSelector;if(this.isXAxis&&(h&&h.enabled||e&&e.enabled))if("x"===
f)c.resetZoomButton="blocked";else if("y"===f)var n=!1;else"xy"===f&&(c=this.previousZoom,y(b)?this.previousZoom=[this.min,this.max]:c&&(b=c[0],d=c[1],delete this.previousZoom));return void 0!==n?n:a.call(this,b,d)});k(D.prototype,"init",function(a,b,d){r(this,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new F(this)});a.call(this,b,d)});k(D.prototype,"setChartSize",function(a){var b=this.legend,d=this.navigator;a.apply(this,
[].slice.call(arguments,1));if(d){var c=b.options;var e=d.xAxis;var h=d.yAxis;var k=d.scrollbarHeight;this.inverted?(d.left=d.opposite?this.chartWidth-k-d.height:this.spacing[3]+k,d.top=this.plotTop+k):(d.left=this.plotLeft+k,d.top=d.navigatorOptions.top||this.chartHeight-d.height-k-this.spacing[2]-("bottom"===c.verticalAlign&&c.enabled&&!c.floating?b.legendHeight+f(c.margin,10):0));e&&h&&(this.inverted?e.options.left=h.options.left=d.left:e.options.top=h.options.top=d.top,e.setAxisSize(),h.setAxisSize())}});
k(u.prototype,"addPoint",function(a,b,d,c,e){var f=this.options.turboThreshold;f&&this.xData.length>f&&g(b,!0)&&this.chart.navigator&&l(20,!0);a.call(this,b,d,c,e)});k(D.prototype,"addSeries",function(a,b,d,c){a=a.call(this,b,!1,c);this.navigator&&this.navigator.setBaseSeries();f(d,!0)&&this.redraw();return a});k(u.prototype,"update",function(a,b,d){a.call(this,b,!1);this.chart.navigator&&this.chart.navigator.setBaseSeries();f(d,!0)&&this.chart.redraw()});D.prototype.callbacks.push(function(a){var b=
a.navigator;b&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))})})(L);(function(a){function F(a){this.init(a)}var r=a.addEvent,A=a.Axis,D=a.Chart,G=a.css,E=a.createElement,y=a.dateFormat,p=a.defaultOptions,x=p.global.useUTC,w=a.defined,J=a.destroyObjectProperties,l=a.discardElement,e=a.each,b=a.extend,c=a.fireEvent,v=a.Date,g=a.isNumber,m=a.merge,f=a.pick,q=a.pInt,C=a.splat,u=a.wrap;b(p,{rangeSelector:{buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,zIndex:7},height:35,inputPosition:{align:"right"},
labelStyle:{color:"#666666"}}});p.lang=m(p.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});F.prototype={clickButton:function(a,b){var d=this,c=d.chart,k=d.buttonOptions[a],h=c.xAxis[0],n=c.scroller&&c.scroller.getUnionExtremes()||h||{},l=n.dataMin,p=n.dataMax,m=h&&Math.round(Math.min(h.max,f(p,h.max))),q=k.type;n=k._range;var u,w=k.dataGrouping;if(null!==l&&null!==p){c.fixedRange=n;w&&(this.forcedDataGrouping=!0,A.prototype.setDataGrouping.call(h||{chart:this.chart},
w,!1));if("month"===q||"year"===q)if(h){q={range:k,max:m,dataMin:l,dataMax:p};var v=h.minFromRange.call(q);g(q.newMax)&&(m=q.newMax)}else n=k;else if(n)v=Math.max(m-n,l),m=Math.min(v+n,p);else if("ytd"===q)if(h)void 0===p&&(l=Number.MAX_VALUE,p=Number.MIN_VALUE,e(c.series,function(a){a=a.xData;l=Math.min(a[0],l);p=Math.max(a[a.length-1],p)}),b=!1),m=d.getYTDExtremes(p,l,x),v=u=m.min,m=m.max;else{r(c,"beforeRender",function(){d.clickButton(a)});return}else"all"===q&&h&&(v=l,m=p);d.setSelected(a);if(h)h.setExtremes(v,
m,f(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:k});else{var N=C(c.options.xAxis)[0];var y=N.range;N.range=n;var D=N.min;N.min=u;r(c,"load",function(){N.range=y;N.min=D})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,d=a.options.rangeSelector,
f=d.buttons||[].concat(b.defaultButtons),g=d.selected,h=function(){var a=b.minInput,d=b.maxInput;a&&a.blur&&c(a,"blur");d&&d.blur&&c(d,"blur")};b.chart=a;b.options=d;b.buttons=[];a.extraTopMargin=d.height;b.buttonOptions=f;this.unMouseDown=r(a.container,"mousedown",h);this.unResize=r(a,"resize",h);e(f,b.computeButtonRange);void 0!==g&&f[g]&&this.clickButton(g,!1);r(a,"load",function(){r(a.xAxis[0],"setExtremes",function(d){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==
d.trigger&&b.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,b=a.xAxis[0],c=Math.round(b.max-b.min),f=!b.hasVisibleSeries;a=a.scroller&&a.scroller.getUnionExtremes()||b;var B=a.dataMin,h=a.dataMax;a=this.getYTDExtremes(h,B,x);var n=a.min,l=a.max,p=this.selected,m=g(p),q=this.options.allButtonsEnabled,r=this.buttons;e(this.buttonOptions,function(a,d){var e=a._range,k=a.type,g=a.count||1,t=r[d],z=0;var H=d===p;var I=e>h-B,K=e<b.minRange,u=!1,w=!1;
e=e===c;("month"===k||"year"===k)&&c>=864E5*{month:28,year:365}[k]*g&&c<=864E5*{month:31,year:366}[k]*g?e=!0:"ytd"===k?(e=l-n===c,u=!H):"all"===k&&(e=b.max-b.min>=h-B,w=!H&&m&&e);k=!q&&(I||K||w||f);H=H&&e||e&&!m&&!u;k?z=3:H&&(m=!0,z=2);t.state!==z&&t.setState(z)})},computeButtonRange:function(a){var b=a.type,d=a.count||1,c={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(c[b])a._range=c[b]*d;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*d},setInputValue:function(a,
b){var d=this.chart.options.rangeSelector,c=this[a+"Input"];w(b)&&(c.previousValue=c.HCTime,c.HCTime=b);c.value=y(d.inputEditDateFormat||"%Y-%m-%d",c.HCTime);this[a+"DateBox"].attr({text:y(d.inputDateFormat||"%b %e, %Y",c.HCTime)})},showInput:function(a){var b=this.inputGroup,d=this[a+"DateBox"];G(this[a+"Input"],{left:b.translateX+d.x+"px",top:b.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})},hideInput:function(a){G(this[a+"Input"],{border:0,width:"1px",height:"1px"});
this.setInputValue(a)},drawInput:function(a){function d(){var a=u.value,b=(n.inputDateParser||Date.parse)(a),d=e.xAxis[0],f=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:d,h=f.dataMin;f=f.dataMax;b!==u.previousValue&&(u.previousValue=b,g(b)||(b=a.split("-"),b=Date.UTC(q(b[0]),q(b[1])-1,q(b[2]))),g(b)&&(x||(b+=6E4*(new Date).getTimezoneOffset()),r?b>c.maxInput.HCTime?b=void 0:b<h&&(b=h):b<c.minInput.HCTime?b=void 0:b>f&&(b=f),void 0!==b&&d.setExtremes(r?b:d.min,r?d.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}
var c=this,e=c.chart,f=e.renderer.style||{},h=e.renderer,n=e.options.rangeSelector,l=c.div,r="min"===a,u,w,v=this.inputGroup;this[a+"Label"]=w=h.label(p.lang[r?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(v);v.offset+=w.width+5;this[a+"DateBox"]=h=h.label("",v.offset).addClass("highcharts-range-input").attr({padding:2,width:n.inputBoxWidth||90,height:n.inputBoxHeight||17,stroke:n.inputBoxBorderColor||"#cccccc","stroke-width":1,
"text-align":"center"}).on("click",function(){c.showInput(a);c[a+"Input"].focus()}).add(v);v.offset+=h.width+(r?10:0);this[a+"Input"]=u=E("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},l);w.css(m(f,n.labelStyle));h.css(m({color:"#333333"},f,n.inputStyle));G(u,b({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:f.fontSize,fontFamily:f.fontFamily,left:"-9em"},n.inputStyle));u.onfocus=function(){c.showInput(a)};u.onblur=
function(){c.hideInput(a)};u.onchange=d;u.onkeypress=function(a){13===a.keyCode&&d()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector;a=f((b.buttonPosition||{}).y,a.plotTop-a.axisOffset[0]-b.height);return{buttonTop:a,inputTop:a-10}},getYTDExtremes:function(a,b,c){var d=new v(a),e=d[v.hcGetFullYear]();c=c?v.UTC(e,0,1):+new v(e,0,1);b=Math.max(b||0,c);d=d.getTime();return{max:Math.min(a||d,d),min:b}},render:function(a,c){var d=this,g=d.chart,k=g.renderer,h=g.container,n=g.options,
l=n.exporting&&!1!==n.exporting.enabled&&n.navigation&&n.navigation.buttonOptions,m=n.rangeSelector,q=d.buttons;n=p.lang;var r=d.div;r=d.inputGroup;var u=m.buttonTheme,v=m.buttonPosition||{},x=m.inputEnabled,y=u&&u.states,A=g.plotLeft,C=this.getPosition(),D=d.group,F=d.rendered;if(!1!==m.enabled){if(!F){d.group=D=k.g("range-selector-buttons").add();d.zoomText=k.text(n.rangeSelectorZoom,f(v.x,A),15).css(m.labelStyle).add(D);var G=f(v.x,A)+d.zoomText.getBBox().width+5;e(d.buttonOptions,function(a,b){q[b]=
k.button(a.text,G,0,function(){d.clickButton(b);d.isActive=!0},u,y&&y.hover,y&&y.select,y&&y.disabled).attr({"text-align":"center"}).add(D);G+=q[b].width+f(m.buttonSpacing,5)});!1!==x&&(d.div=r=E("div",null,{position:"relative",height:0,zIndex:1}),h.parentNode.insertBefore(r,h),d.inputGroup=r=k.g("input-group").add(),r.offset=0,d.drawInput("min"),d.drawInput("max"))}d.updateButtonStates();D[F?"animate":"attr"]({translateY:C.buttonTop});!1!==x&&(r.align(b({y:C.inputTop,width:r.offset,x:l&&C.inputTop<
(l.y||0)+l.height-g.spacing[0]?-40:0},m.inputPosition),!0,g.spacingBox),w(x)||(g=D.getBBox(),r[r.alignAttr.translateX<g.x+g.width+10?"hide":"show"]()),d.setInputValue("min",a),d.setInputValue("max",c));d.rendered=!0}},update:function(a){var b=this.chart;m(!0,b.options.rangeSelector,a);this.destroy();this.init(b)},destroy:function(){var b=this,c=b.minInput,e=b.maxInput;b.unMouseDown();b.unResize();J(b.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);e&&(e.onfocus=e.onblur=e.onchange=null);a.objectEach(b,
function(a,d){a&&"chart"!==d&&(a.destroy?a.destroy():a.nodeType&&l(this[d]));a!==F.prototype[d]&&(b[d]=null)},this)}};A.prototype.toFixedRange=function(a,b,c,e){var d=this.chart&&this.chart.fixedRange;a=f(c,this.translate(a,!0,!this.horiz));b=f(e,this.translate(b,!0,!this.horiz));c=d&&(b-a)/d;.7<c&&1.3>c&&(e?a=b-d:b=a+d);g(a)||(a=b=void 0);return{min:a,max:b}};A.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],c=this.max,e=function(a,c){var d=new Date(a),
e=d["get"+b]();d["set"+b](e+c);e===d["get"+b]()&&d.setDate(0);return d.getTime()-a};if(g(a)){var l=c-a;var h=a}else l=c+e(c,-a.count),this.chart&&(this.chart.fixedRange=c-l);var n=f(this.dataMin,Number.MIN_VALUE);g(l)||(l=n);l<=n&&(l=n,void 0===h&&(h=e(l,a.count)),this.newMax=Math.min(l+h,this.dataMax));g(c)||(l=void 0);return l};u(D.prototype,"init",function(a,b,c){r(this,"init",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new F(this))});a.call(this,b,c)});D.prototype.callbacks.push(function(a){function b(){c=
a.xAxis[0].getExtremes();g(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector;if(d){var e=r(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var f=r(a,"redraw",b);b()}r(a,"destroy",function(){d&&(f(),e())})});a.RangeSelector=F})(L);(function(a){var F=a.arrayMax,r=a.arrayMin,A=a.Axis,D=a.Chart,G=a.defined,E=a.each,y=a.extend,p=a.format,x=a.grep,w=a.inArray,J=a.isNumber,l=a.isString,e=a.map,b=a.merge,c=a.pick,v=a.Point,g=a.Renderer,m=a.Series,f=a.splat,q=a.SVGRenderer,C=a.VMLRenderer,
u=a.wrap,d=m.prototype,k=d.init,t=d.processData,H=v.prototype.tooltipFormatter;a.StockChart=a.stockChart=function(d,h,g){var n=l(d)||d.nodeName,k=arguments[n?1:0],m=k.series,p=a.getOptions(),q,B=c(k.navigator&&k.navigator.enabled,p.navigator.enabled,!0),r=B?{startOnTick:!1,endOnTick:!1}:null,t={marker:{enabled:!1,radius:2}},u={shadow:!1,borderWidth:0};k.xAxis=e(f(k.xAxis||{}),function(a){return b({minPadding:0,maxPadding:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},
p.xAxis,a,{type:"datetime",categories:null},r)});k.yAxis=e(f(k.yAxis||{}),function(a){q=c(a.opposite,!0);return b({labels:{y:-2},opposite:q,showLastLabel:!1,title:{text:null}},p.yAxis,a)});k.series=null;k=b({chart:{panning:!0,pinchType:"x"},navigator:{enabled:B},scrollbar:{enabled:c(p.scrollbar.enabled,!0)},rangeSelector:{enabled:c(p.rangeSelector.enabled,!0)},title:{text:null},tooltip:{shared:!0,crosshairs:!0},legend:{enabled:!1},plotOptions:{line:t,spline:t,area:t,areaspline:t,arearange:t,areasplinerange:t,
column:u,columnrange:u,candlestick:u,ohlc:u}},k,{isStock:!0});k.series=m;return n?new D(d,k,g):new D(k,h)};u(A.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var d=this.options.labels;return this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.call(this,[].slice.call(arguments,1))});u(A.prototype,"destroy",function(a){var b=this.chart,
c=this.options&&this.options.top+","+this.options.height;c&&b._labelPanes&&b._labelPanes[c]===this&&delete b._labelPanes[c];return a.call(this,Array.prototype.slice.call(arguments,1))});u(A.prototype,"getPlotLinePath",function(b,d,f,g,k,m){var h=this,n=this.isLinked&&!this.series?this.linkedParent.series:this.series,p=h.chart,q=p.renderer,r=h.left,t=h.top,B,u,z,v,x=[],y=[];if("colorAxis"===h.coll)return b.apply(this,[].slice.call(arguments,1));y=function(a){var b="xAxis"===a?"yAxis":"xAxis";a=h.options[b];
return J(a)?[p[b][a]]:l(a)?[p.get(a)]:e(n,function(a){return a[b]})}(h.coll);E(h.isXAxis?p.yAxis:p.xAxis,function(a){if(G(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=G(a.options[b])?p[b][a.options[b]]:p[b][0];h===b&&y.push(a)}});var A=y.length?[]:[h.isXAxis?p.yAxis[0]:p.xAxis[0]];E(y,function(b){-1!==w(b,A)||a.find(A,function(a){return a.pos===b.pos&&a.len&&b.len})||A.push(b)});var C=c(m,h.translate(d,null,null,g));J(C)&&(h.horiz?E(A,function(a){var b;
u=a.pos;v=u+a.len;B=z=Math.round(C+h.transB);if(B<r||B>r+h.width)k?B=z=Math.min(Math.max(r,B),r+h.width):b=!0;b||x.push("M",B,u,"L",z,v)}):E(A,function(a){var b;B=a.pos;z=B+a.len;u=v=Math.round(t+h.height-C);if(u<t||u>t+h.height)k?u=v=Math.min(Math.max(t,u),h.top+h.height):b=!0;b||x.push("M",B,u,"L",z,v)}));return 0<x.length?q.crispPolyLine(x,f||1):null});A.prototype.getPlotBandPath=function(a,b){var c=this.getPlotLinePath(b,null,null,!0),d=this.getPlotLinePath(a,null,null,!0),e=[],f;if(d&&c)if(d.toString()===
c.toString())e=d,e.isFlat=!0;else for(f=0;f<d.length;f+=6)e.push("M",d[f+1],d[f+2],"L",d[f+4],d[f+5],c[f+4],c[f+5],c[f+1],c[f+2],"z");else e=null;return e};q.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};g===C&&(C.prototype.crispPolyLine=q.prototype.crispPolyLine);u(A.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=
this.crossLabel.hide())});u(A.prototype,"drawCrosshair",function(a,b,d){var e,f;a.call(this,b,d);if(G(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){a=this.chart;var h=this.options.crosshair.label,g=this.horiz,k=this.opposite,l=this.left,n=this.top,m=this.crossLabel,q=h.format,r="",u="inside"===this.options.tickPosition,t=!1!==this.crosshair.snap,v=0;b||(b=this.cross&&this.cross.e);var B=g?"center":k?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";
m||(m=this.crossLabel=a.renderer.label(null,null,null,h.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:h.align||B,padding:c(h.padding,8),r:c(h.borderRadius,3),zIndex:2}).add(this.labelGroup),m.attr({fill:h.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:h.borderColor||"","stroke-width":h.borderWidth||0}).css(y({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},h.style)));
g?(B=t?d.plotX+l:b.chartX,n+=k?0:this.height):(B=k?this.width+l:0,n=t?d.plotY+n:b.chartY);q||h.formatter||(this.isDatetimeAxis&&(r="%b %d, %Y"),q="{value"+(r?":"+r:"")+"}");b=t?d[this.isXAxis?"x":"y"]:this.toValue(g?b.chartX:b.chartY);m.attr({text:q?p(q,{value:b}):h.formatter.call(this,b),x:B,y:n,visibility:"visible"});b=m.getBBox();if(g){if(u&&!k||!u&&k)n=m.y-b.height}else n=m.y-b.height/2;g?(e=l-b.x,f=l+this.width-b.x):(e="left"===this.labelAlign?l:0,f="right"===this.labelAlign?l+this.width:a.chartWidth);
m.translateX<e&&(v=e-m.translateX);m.translateX+b.width>=f&&(v=-(m.translateX+b.width-f));m.attr({x:B+v,y:n,anchorX:g?B:this.opposite?0:a.chartWidth,anchorY:g?this.opposite?a.chartHeight:0:n+b.height/2})}});d.init=function(){k.apply(this,arguments);this.setCompare(this.options.compare)};d.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=
b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};d.processData=function(){var a,b=-1;t.apply(this,arguments);if(this.xAxis&&this.processedYData){var c=this.processedXData;var d=this.processedYData;var e=d.length;this.pointArrayMap&&(b=w("close",this.pointArrayMap),-1===b&&(b=w(this.pointValKey||"y",this.pointArrayMap)));for(a=0;a<e-1;a++){var f=d[a]&&-1<b?d[a][b]:d[a];if(J(f)&&c[a+1]>=this.xAxis.min&&0!==f){this.compareValue=f;break}}}};u(d,"getExtremes",function(a){a.apply(this,
[].slice.call(arguments,1));if(this.modifyValue){var b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=r(b);this.dataMax=F(b)}});A.prototype.setCompare=function(a,b){this.isXAxis||(E(this.series,function(b){b.setCompare(a)}),c(b,!0)&&this.chart.redraw())};v.prototype.tooltipFormatter=function(b){b=b.replace("{point.change}",(0<this.change?"+":"")+a.numberFormat(this.change,c(this.series.tooltipOptions.changeDecimals,2)));return H.apply(this,[b])};u(m.prototype,"render",
function(a){this.chart.is3d&&this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(!this.clipBox&&this.animate?(this.clipBox=b(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:this.yAxis.len}):this.clipBox&&(this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len));a.call(this)});u(D.prototype,"getSelectedPoints",function(a){var b=
a.call(this);E(this.series,function(a){a.hasGroupedData&&(b=b.concat(x(a.points||[],function(a){return a.selected})))});return b});u(D.prototype,"update",function(a,c){"scrollbar"in c&&this.navigator&&(b(!0,this.options.scrollbar,c.scrollbar),this.navigator.update({},!1),delete c.scrollbar);return a.apply(this,Array.prototype.slice.call(arguments,1))})})(L)});