/*
 Highcharts JS v5.0.11 (2018-09-19)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(J){"object"===typeof module&&module.exports?module.exports=J:J(Highcharts)})(function(J){(function(a){var D=a.addEvent,p=a.Axis,n=a.Chart,z=a.css,F=a.dateFormat,y=a.defined,H=a.each,G=a.extend,f=a.noop,w=a.timeUnits,t=a.wrap;t(a.Series.prototype,"init",function(a){var m;a.apply(this,Array.prototype.slice.call(arguments,1));(m=this.xAxis)&&m.options.ordinal&&D(this,"updatedData",function(){delete m.ordinalIndex})});t(p.prototype,"getTimeTicks",function(a,k,b,d,C,l,f,g){var q=0,u,m,c={},e=
[],h=-Number.MAX_VALUE,A=this.options.tickPixelInterval;if(!this.options.ordinal&&!this.options.breaks||!l||3>l.length||void 0===b)return a.call(this,k,b,d,C);var r=l.length;for(u=0;u<r;u++){var x=u&&l[u-1]>d;l[u]<b&&(q=u);if(u===r-1||l[u+1]-l[u]>5*f||x){if(l[u]>h){for(m=a.call(this,k,l[q],l[u],C);m.length&&m[0]<=h;)m.shift();m.length&&(h=m[m.length-1]);e=e.concat(m)}q=u+1}if(x)break}a=m.info;if(g&&a.unitRange<=w.hour){u=e.length-1;for(q=1;q<u;q++)if(F("%d",e[q])!==F("%d",e[q-1])){c[e[q]]="day";var v=
!0}v&&(c[e[0]]="day");a.higherRanks=c}e.info=a;if(g&&y(A)){g=a=e.length;u=[];var B;for(v=[];g--;)q=this.translate(e[g]),B&&(v[g]=B-q),u[g]=B=q;v.sort();v=v[Math.floor(v.length/2)];v<.6*A&&(v=null);g=e[a-1]>d?a-1:a;for(B=void 0;g--;)q=u[g],d=Math.abs(B-q),B&&d<.8*A&&(null===v||d<.8*v)?(c[e[g]]&&!c[e[g+1]]?(d=g+1,B=q):d=g,e.splice(d,1)):B=q}return e});G(p.prototype,{beforeSetTickPositions:function(){var a=[],k=!1,b=this.getExtremes(),d=b.min,C=b.max,l,f=this.isXAxis&&!!this.options.breaks;b=this.options.ordinal;
var g=this.chart.options.chart.ignoreHiddenSeries;if(b||f){H(this.series,function(b,c){if(!(g&&!1===b.visible||!1===b.takeOrdinalPosition&&!f)&&(a=a.concat(b.processedXData),q=a.length,a.sort(function(c,h){return c-h}),q))for(c=q-1;c--;)a[c]===a[c+1]&&a.splice(c,1)});var q=a.length;if(2<q){var u=a[1]-a[0];for(l=q-1;l--&&!k;)a[l+1]-a[l]!==u&&(k=!0);!this.options.keepOrdinalPadding&&(a[0]-d>u||C-a[a.length-1]>u)&&(k=!0)}k?(this.ordinalPositions=a,u=this.ordinal2lin(Math.max(d,a[0]),!0),l=Math.max(this.ordinal2lin(Math.min(C,
a[a.length-1]),!0),1),this.ordinalSlope=C=(C-d)/(l-u),this.ordinalOffset=d-u*C):this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0}this.isOrdinal=b&&k;this.groupIntervalFactor=null},val2lin:function(a,k){var b=this.ordinalPositions,d;if(b){var m=b.length;for(d=m;d--;)if(b[d]===a){var l=d;break}for(d=m-1;d--;)if(a>b[d]||0===d){b=(a-b[d])/(b[d+1]-b[d]);l=d+b;break}d=k?l:this.ordinalSlope*(l||0)+this.ordinalOffset}else d=a;return d},lin2val:function(a,k){var b=this.ordinalPositions;if(b){var d=
this.ordinalSlope,m=this.ordinalOffset,l=b.length-1;if(k)if(0>a)a=b[0];else if(a>l)a=b[l];else{l=Math.floor(a);var f=a-l}else for(;l--;){var g=d*l+m;if(a>=g){d=d*(l+1)+m;f=(a-g)/(d-g);break}}return void 0!==f&&void 0!==b[l]?b[l]+(f?f*(b[l+1]-b[l]):0):a}return a},getExtendedPositions:function(){var a=this.chart,k=this.series[0].currentDataGrouping,b=this.ordinalIndex,d=k?k.count+k.unitName:"raw",C=this.getExtremes(),l;b||(b=this.ordinalIndex={});if(!b[d]){var t={series:[],chart:a,getExtremes:function(){return{min:C.dataMin,
max:C.dataMax}},options:{ordinal:!0},val2lin:p.prototype.val2lin,ordinal2lin:p.prototype.ordinal2lin};H(this.series,function(g){l={xAxis:t,xData:g.xData,chart:a,destroyGroupedData:f};l.options={dataGrouping:k?{enabled:!0,forced:!0,approximation:"open",units:[[k.unitName,[k.count]]]}:{enabled:!1}};g.processData.apply(l);t.series.push(l)});this.beforeSetTickPositions.apply(t);b[d]=t.ordinalPositions}return b[d]},getGroupIntervalFactor:function(a,k,b){b=b.processedXData;var d=b.length,f=[];var l=this.groupIntervalFactor;
if(!l){for(l=0;l<d-1;l++)f[l]=b[l+1]-b[l];f.sort(function(a,g){return a-g});f=f[Math.floor(d/2)];a=Math.max(a,b[0]);k=Math.min(k,b[d-1]);this.groupIntervalFactor=l=d*f/(k-a)}return l},postProcessTickInterval:function(a){var k=this.ordinalSlope;return k?this.options.breaks?this.closestPointRange:a/(k/this.closestPointRange):a}});p.prototype.ordinal2lin=p.prototype.val2lin;t(n.prototype,"pan",function(a,k){var b=this.xAxis[0],d=k.chartX,f=!1;if(b.options.ordinal&&b.series.length){var l=this.mouseDownX,
m=b.getExtremes(),g=m.dataMax,q=m.min,u=m.max,t=this.hoverPoints,c=b.closestPointRange;l=(l-d)/(b.translationSlope*(b.ordinalSlope||c));var e={ordinalPositions:b.getExtendedPositions()};c=b.lin2val;var h=b.val2lin;if(!e.ordinalPositions)f=!0;else if(1<Math.abs(l)){t&&H(t,function(r){r.setState()});if(0>l){t=e;var A=b.ordinalPositions?b:e}else t=b.ordinalPositions?b:e,A=e;e=A.ordinalPositions;g>e[e.length-1]&&e.push(g);this.fixedRange=u-q;l=b.toFixedRange(null,null,c.apply(t,[h.apply(t,[q,!0])+l,!0]),
c.apply(A,[h.apply(A,[u,!0])+l,!0]));l.min>=Math.min(m.dataMin,q)&&l.max<=Math.max(g,u)&&b.setExtremes(l.min,l.max,!0,!1,{trigger:"pan"});this.mouseDownX=d;z(this.container,{cursor:"move"})}}else f=!0;f&&a.apply(this,Array.prototype.slice.call(arguments,1))})})(J);(function(a){function D(){return Array.prototype.slice.call(arguments,1)}function p(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,n(this.pointArrayMap,["y"]))}var n=a.pick,z=a.wrap,F=a.each,y=a.extend,H=a.isArray,
G=a.fireEvent,f=a.Axis,w=a.Series;y(f.prototype,{isInBreak:function(a,f){var k=a.repeat||Infinity,b=a.from,d=a.to-a.from;k=f>=b?(f-b)%k:k-(b-f)%k;return a.inclusive?k<=d:k<d&&0!==k},isInAnyBreak:function(a,f){var k=this.options.breaks,b=k&&k.length,d;if(b){for(;b--;)if(this.isInBreak(k[b],a)){var m=!0;d||(d=n(k[b].showPoints,this.isXAxis?!1:!0))}var l=m&&f?m&&!d:m}return l}});z(f.prototype,"setTickPositions",function(a){a.apply(this,Array.prototype.slice.call(arguments,1));if(this.options.breaks){var f=
this.tickPositions,k=this.tickPositions.info,b=[],d;for(d=0;d<f.length;d++)this.isInAnyBreak(f[d])||b.push(f[d]);this.tickPositions=b;this.tickPositions.info=k}});z(f.prototype,"init",function(a,m,k){var b=this;k.breaks&&k.breaks.length&&(k.ordinal=!1);a.call(this,m,k);a=this.options.breaks;b.isBroken=H(a)&&!!a.length;b.isBroken&&(b.val2lin=function(a){var d=a,l;for(l=0;l<b.breakArray.length;l++){var f=b.breakArray[l];if(f.to<=a)d-=f.len;else if(f.from>=a)break;else if(b.isInBreak(f,a)){d-=a-f.from;
break}}return d},b.lin2val=function(a){var d;for(d=0;d<b.breakArray.length;d++){var f=b.breakArray[d];if(f.from>=a)break;else f.to<a?a+=f.len:b.isInBreak(f,a)&&(a+=f.len)}return a},b.setExtremes=function(a,b,l,k,g){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(b);)b-=this.closestPointRange;f.prototype.setExtremes.call(this,a,b,l,k,g)},b.setAxisTranslation=function(a){f.prototype.setAxisTranslation.call(this,a);a=b.options.breaks;var d=[],l=[],k=0,g,q=b.userMin||b.min,
u=b.userMax||b.max,m=n(b.pointRangePadding,0),c;F(a,function(c){g=c.repeat||Infinity;b.isInBreak(c,q)&&(q+=c.to%g-q%g);b.isInBreak(c,u)&&(u-=u%g-c.from%g)});F(a,function(e){h=e.from;for(g=e.repeat||Infinity;h-g>q;)h-=g;for(;h<q;)h+=g;for(c=h;c<u;c+=g)d.push({value:c,move:"in"}),d.push({value:c+(e.to-e.from),move:"out",size:e.breakSize})});d.sort(function(c,r){return c.value===r.value?("in"===c.move?0:1)-("in"===r.move?0:1):c.value-r.value});var e=0;var h=q;F(d,function(c){e+="in"===c.move?1:-1;1===
e&&"in"===c.move&&(h=c.value);0===e&&(l.push({from:h,to:c.value,len:c.value-h-(c.size||0)}),k+=c.value-h-(c.size||0))});b.breakArray=l;b.unitLength=u-q-k+m;G(b,"afterBreaks");b.options.staticScale?b.transA=b.options.staticScale:b.unitLength&&(b.transA*=(u-b.min+m)/b.unitLength);m&&(b.minPixelPadding=b.transA*b.minPointOffset);b.min=q;b.max=u})});z(w.prototype,"generatePoints",function(a){a.apply(this,D(arguments));var f=this.xAxis,k=this.yAxis,b=this.points,d=b.length,t=this.options.connectNulls;
if(f&&k&&(f.options.breaks||k.options.breaks))for(;d--;){var l=b[d];var w=null===l.y&&!1===t;w||!f.isInAnyBreak(l.x,!0)&&!k.isInAnyBreak(l.y,!0)||(b.splice(d,1),this.data[d]&&this.data[d].destroyElements())}});a.Series.prototype.drawBreaks=function(a,f){var k=this,b=k.points,d,m,l,w;a&&F(f,function(g){d=a.breakArray||[];m=a.isXAxis?a.min:n(k.options.threshold,a.min);F(b,function(b){w=n(b["stack"+g.toUpperCase()],b[g]);F(d,function(g){l=!1;if(m<g.from&&w>g.to||m>g.from&&w<g.from)l="pointBreak";else if(m<
g.from&&w>g.from&&w<g.to||m>g.from&&w>g.to&&w<g.from)l="pointInBreak";l&&G(a,l,{point:b,brk:g})})})})};a.Series.prototype.gappedPath=function(){var a=this.options.gapSize,f=this.points.slice(),k=f.length-1;if(a&&0<k)for(;k--;)f[k+1].x-f[k].x>this.closestPointRange*a&&f.splice(k+1,0,{isNull:!0});return this.getGraphPath(f)};z(a.seriesTypes.column.prototype,"drawPoints",p);z(a.Series.prototype,"drawPoints",p)})(J);(function(a){var D=a.arrayMax,p=a.arrayMin,n=a.Axis,z=a.defaultPlotOptions,F=a.defined,
y=a.each,H=a.extend,G=a.format,f=a.isNumber,w=a.merge,t=a.pick,m=a.Point,k=a.Tooltip,b=a.wrap,d=a.Series.prototype,C=d.processData,l=d.generatePoints,I=d.destroy,g={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y",
"%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},q={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},u=a.defaultDataGroupingUnits=[["millisecond",
[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],E={sum:function(c){var a=c.length;if(!a&&c.hasNulls)var h=null;else if(a)for(h=0;a--;)h+=c[a];return h},average:function(c){var a=c.length;c=E.sum(c);f(c)&&a&&(c/=a);return c},averages:function(){var c=[];y(arguments,function(a){c.push(E.average(a))});return c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?
D(c):c.hasNulls?null:void 0},low:function(c){return c.length?p(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,h,g){c=E.open(c);a=E.high(a);h=E.low(h);g=E.close(g);if(f(c)||f(a)||f(h)||f(g))return[c,a,h,g]},range:function(c,a){c=E.low(c);a=E.high(a);if(f(c)||f(a))return[c,a]}};d.groupData=function(c,a,h,b){var r=this.data,e=this.options.data,v=[],B=[],A=[],L=c.length,d=!!a,u=[];b="function"===typeof b?b:E[b]||q[this.type]&&E[q[this.type].approximation]||
E[g.approximation];var l=this.pointArrayMap,k=l&&l.length,m=0;var w=0;var t;k?y(l,function(){u.push([])}):u.push([]);var C=k||1;for(t=0;t<=L&&!(c[t]>=h[0]);t++);for(t;t<=L;t++){for(;void 0!==h[m+1]&&c[t]>=h[m+1]||t===L;){var p=h[m];this.dataGroupInfo={start:w,length:u[0].length};w=b.apply(this,u);void 0!==w&&(v.push(p),B.push(w),A.push(this.dataGroupInfo));w=t;for(p=0;p<C;p++)u[p].length=0,u[p].hasNulls=!1;m+=1;if(t===L)break}if(t===L)break;if(l){p=this.cropStart+t;var F=r&&r[p]||this.pointClass.prototype.applyOptions.apply({series:this},
[e[p]]);for(p=0;p<k;p++){var n=F[l[p]];f(n)?u[p].push(n):null===n&&(u[p].hasNulls=!0)}}else p=d?a[t]:null,f(p)?u[0].push(p):null===p&&(u[0].hasNulls=!0)}return[v,B,A]};d.processData=function(){var a=this.chart,e=this.options.dataGrouping,h=!1!==this.allowDG&&e&&t(e.enabled,a.options.isStock),g=this.visible||!a.options.chart.ignoreHiddenSeries,r;this.forceCrop=h;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==C.apply(this,arguments)&&h){this.destroyGroupedData();var x=this.processedXData,v=
this.processedYData,b=a.plotSizeX;a=this.xAxis;var q=a.options.ordinal,f=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(f){this.isDirty=r=!0;var l=a.getExtremes();h=l.min;l=l.max;q=q&&a.getGroupIntervalFactor(h,l,this)||1;b=f*(l-h)/b*q;f=a.getTimeTicks(a.normalizeTimeTickInterval(b,e.units||u),Math.min(h,x[0]),Math.max(l,x[x.length-1]),a.options.startOfWeek,x,this.closestPointRange);x=d.groupData.apply(this,[x,v,f,e.approximation]);v=x[0];q=x[1];if(e.smoothed){e=v.length-1;for(v[e]=
Math.min(v[e],l);e--&&0<e;)v[e]+=b/2;v[0]=Math.max(v[0],h)}this.currentDataGrouping=f.info;this.closestPointRange=f.info.totalRange;this.groupMap=x[2];F(v[0])&&v[0]<a.dataMin&&g&&(a.min===a.dataMin&&(a.min=v[0]),a.dataMin=v[0]);this.processedXData=v;this.processedYData=q}else this.currentDataGrouping=this.groupMap=null;this.hasGroupedData=r}};d.destroyGroupedData=function(){var a=this.groupedData;y(a||[],function(c,h){c&&(a[h]=c.destroy?c.destroy():null)});this.groupedData=null};d.generatePoints=
function(){l.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};b(m.prototype,"update",function(c){this.dataGroup?a.error(24):c.apply(this,[].slice.call(arguments,1))});b(k.prototype,"tooltipFooterHeaderFormatter",function(c,e,h){var g=e.series,r=g.tooltipOptions,x=g.options.dataGrouping,v=r.xDateFormat,b=g.xAxis,q=a.dateFormat;if(b&&"datetime"===b.options.type&&x&&f(e.key)){c=g.currentDataGrouping;x=x.dateTimeLabelFormats;if(c)if(b=x[c.unitName],1===c.count)v=
b[0];else{v=b[1];var d=b[2]}else!v&&x&&(v=this.getXDateFormat(e,r,b));v=q(v,e.key);d&&(v+=q(d,e.key+c.totalRange-1));return G(r[(h?"footer":"header")+"Format"],{point:H(e.point,{key:v}),series:g})}return c.call(this,e,h)});d.destroy=function(){for(var a=this.groupedData||[],g=a.length;g--;)a[g]&&a[g].destroy();I.apply(this)};b(d,"setOptions",function(a,e){var c=a.call(this,e),b=this.type,r=this.chart.options.plotOptions,x=z[b].dataGrouping;q[b]&&(x||(x=w(g,q[b])),c.dataGrouping=w(x,r.series&&r.series.dataGrouping,
r[b].dataGrouping,e.dataGrouping));this.chart.options.isStock&&(this.requireSorting=!0);return c});b(n.prototype,"setScale",function(a){a.call(this);y(this.series,function(a){a.hasProcessed=!1})});n.prototype.getGroupPixelWidth=function(){var a=this.series,g=a.length,h,b=0,r=!1,x;for(h=g;h--;)(x=a[h].options.dataGrouping)&&(b=Math.max(b,x.groupPixelWidth));for(h=g;h--;)(x=a[h].options.dataGrouping)&&a[h].hasProcessed&&(g=(a[h].processedXData||a[h].data).length,a[h].groupPixelWidth||g>this.chart.plotSizeX/
b||g&&x.forced)&&(r=!0);return r?b:0};n.prototype.setDataGrouping=function(a,g){var c;g=t(g,!0);a||(a={forced:!1,units:null});if(this instanceof n)for(c=this.series.length;c--;)this.series[c].update({dataGrouping:a},!1);else y(this.chart.options.series,function(c){c.dataGrouping=a},!1);g&&this.chart.redraw()}})(J);(function(a){var D=a.each,p=a.Point,n=a.seriesType,z=a.seriesTypes;n("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span class="highcharts-color-{point.colorIndex}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},pointValKey:"close",translate:function(){var a=this,p=a.yAxis,n=!!a.modifyValue,G=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];z.column.prototype.translate.apply(a);D(a.points,function(f){D([f.open,f.high,f.low,f.close,f.low],function(w,t){null!==w&&(n&&(w=a.modifyValue(w)),f[G[t]]=p.toPixels(w,!0))});f.tooltipPos[1]=f.plotHigh+p.pos-a.chart.plotTop})},drawPoints:function(){var a=
this,p=a.chart;D(a.points,function(n){var y=n.graphic,f=!y;if(void 0!==n.plotY){y||(n.graphic=y=p.renderer.path().add(a.group));var w=y.strokeWidth()%2/2;var t=Math.round(n.plotX)-w;var m=Math.round(n.shapeArgs.width/2);var k=["M",t,Math.round(n.yBottom),"L",t,Math.round(n.plotHigh)];if(null!==n.open){var b=Math.round(n.plotOpen)+w;k.push("M",t,b,"L",t-m,b)}null!==n.close&&(b=Math.round(n.plotClose)+w,k.push("M",t,b,"L",t+m,b));y[f?"attr":"animate"]({d:k}).addClass(n.getClassName(),!0)}})},animate:null},
{getClassName:function(){return p.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(J);(function(a){var D=a.defaultPlotOptions,p=a.each,n=a.merge;a=a.seriesType;a("candlestick","ohlc",n(D.column,{states:{hover:{lineWidth:2}},tooltip:D.ohlc.tooltip,threshold:null}),{drawPoints:function(){var a=this,n=a.chart;p(a.points,function(p){var y=p.graphic,z=!y;if(void 0!==p.plotY){y||(p.graphic=y=n.renderer.path().add(a.group));var f=y.strokeWidth()%
2/2;var w=Math.round(p.plotX)-f;var t=p.plotOpen;var m=p.plotClose;var k=Math.min(t,m);t=Math.max(t,m);var b=Math.round(p.shapeArgs.width/2);m=Math.round(k)!==Math.round(p.plotHigh);var d=t!==p.yBottom;k=Math.round(k)+f;t=Math.round(t)+f;f=[];f.push("M",w-b,t,"L",w-b,k,"L",w+b,k,"L",w+b,t,"Z","M",w,k,"L",w,m?Math.round(p.plotHigh):k,"M",w,t,"L",w,d?Math.round(p.yBottom):t);y[z?"attr":"animate"]({d:f}).addClass(p.getClassName(),!0)}})}})})(J);(function(a){var D=a.addEvent,p=a.each,n=a.noop,z=a.seriesType,
F=a.seriesTypes,y=a.TrackerMixin,H=a.SVGRenderer.prototype.symbols,G=a.stableSort;z("flags","column",{pointRange:0,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,translate:function(){F.column.prototype.translate.apply(this);var a=this.options,w=this.chart,t=this.points,m=t.length-1,k,b=a.onSeries;var d=
b&&w.get(b);a=a.onKey||"y";b=d&&d.options.step;var n=d&&d.points,l=n&&n.length,y=this.xAxis,g=this.yAxis,q=y.getExtremes(),u=0,E;if(d&&d.visible&&l){u=(d.pointXOffset||0)+(d.barW||0)/2;d=d.currentDataGrouping;var c=n[l-1].x+(d?d.totalRange:0);G(t,function(a,c){return a.x-c.x});for(a="plot"+a[0].toUpperCase()+a.substr(1);l--&&t[m];){d=t[m];var e=n[l];if(e.x<=d.x&&void 0!==e[a]&&(d.x<=c&&(d.plotY=e[a],e.x<d.x&&!b&&(E=n[l+1])&&void 0!==E[a]&&(d.plotY+=(d.x-e.x)/(E.x-e.x)*(E[a]-e[a]))),m--,l++,0>m))break}}p(t,
function(a,c){void 0===a.plotY&&(a.x>=q.min&&a.x<=q.max?a.plotY=w.chartHeight-y.bottom-(y.opposite?y.height:0)+y.offset-g.top:a.shapeArgs={});a.plotX+=u;if((k=t[c-1])&&k.plotX===a.plotX){void 0===k.stackIndex&&(k.stackIndex=0);var r=k.stackIndex+1}a.stackIndex=r})},drawPoints:function(){var f=this.points,w=this.chart,p=w.renderer,m=this.options,k=m.y,b,d=this.yAxis;for(b=f.length;b--;){var n=f[b];var l=n.plotX>this.xAxis.len;var y=n.plotX;var g=n.stackIndex;var q=n.options.shape||m.shape;var u=n.plotY;
void 0!==u&&(u=n.plotY+k-(void 0!==g&&g*m.stackDistance));var E=g?void 0:n.plotX;var c=g?void 0:n.plotY;g=n.graphic;void 0!==u&&0<=y&&!l?(g||(g=n.graphic=p.label("",null,null,q,null,null,m.useHTML).attr({align:"flag"===q?"left":"center",width:m.width,height:m.height,"text-align":m.textAlign}).addClass("highcharts-point").add(this.markerGroup),n.graphic.div&&(n.graphic.div.point=n)),0<y&&(y-=g.strokeWidth()%2),g.attr({text:n.options.title||m.title||"A",x:y,y:u,anchorX:E,anchorY:c}),n.tooltipPos=w.inverted?
[d.len+d.pos-w.plotLeft-u,this.xAxis.len-y]:[y,u+d.pos-w.plotTop]):g&&(n.graphic=g.destroy())}m.useHTML&&a.wrap(this.markerGroup,"on",function(c){return a.SVGElement.prototype.on.apply(c.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;y.drawTrackerPoint.apply(this);p(a,function(f){var n=f.graphic;n&&D(n.element,"mouseover",function(){0<f.stackIndex&&!f.raised&&(f._y=n.y,n.attr({y:f._y-8}),f.raised=!0);p(a,function(a){a!==f&&a.raised&&
a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:n,buildKDTree:n,setClip:n});H.flag=function(a,n,p,m,k){return["M",k&&k.anchorX||a,k&&k.anchorY||n,"L",a,n+m,a,n,a+p,n,a+p,n+m,a,n+m,"Z"]};p(["circle","square"],function(a){H[a+"pin"]=function(f,n,p,k,b){var d=b&&b.anchorX;b=b&&b.anchorY;"circle"===a&&k>p&&(f-=Math.round((k-p)/2),p=k);f=H[a](f,n,p,k);d&&b&&f.push("M",d,n>b?n:n+k,"L",d,b);return f}})})(J);(function(a){function D(a,b,d){this.init(a,b,d)}var p=a.addEvent,n=a.Axis,z=a.correctFloat,
F=a.defaultOptions,y=a.defined,H=a.destroyObjectProperties,G=a.doc,f=a.each,w=a.fireEvent,t=a.hasTouch,m=a.isTouchDevice,k=a.merge,b=a.pick,d=a.removeEvent,C=a.wrap,l,I={height:m?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:a.svg&&!m,margin:10,minWidth:6,step:.2,zIndex:3};F.scrollbar=k(!0,I,F.scrollbar);a.swapXY=l=function(a,b){var g,q=a.length;if(b)for(g=0;g<q;g+=3){var c=a[g+1];a[g+1]=a[g+2];a[g+2]=c}return a};D.prototype={init:function(a,q,d){this.scrollbarButtons=[];this.renderer=a;
this.userOptions=q;this.options=k(I,q);this.chart=d;this.size=b(this.options.size,this.options.height);q.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,b=this.options,d=this.size,f;this.group=f=a.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||0,height:d,width:d}).add(f);this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%
2/2});this.scrollbarGroup=a.g().add(f);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:d,width:d,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(l(["M",-3,d/4,"L",-3,2*d/3,"M",0,d/4,"L",0,2*d/3,"M",3,d/4,"L",3,2*d/3],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);
this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,b,d,f){var c=this.options.vertical,g=0,h=this.rendered?"animate":"attr";this.x=a;this.y=b+this.trackBorderWidth;this.width=d;this.xOffset=this.height=f;this.yOffset=g;c?(this.width=this.yOffset=d=g=this.size,this.xOffset=b=0,this.barWidth=f-2*d,this.x=a+=this.options.margin):(this.height=this.xOffset=f=b=this.size,this.barWidth=d-2*f,this.y+=this.options.margin);this.group[h]({translateX:a,translateY:this.y});this.track[h]({width:d,
height:f});this.scrollbarButtons[1][h]({translateX:c?0:d-b,translateY:c?f-g:0})},drawScrollbarButton:function(a){var g=this.renderer,b=this.scrollbarButtons,d=this.options,c=this.size;var e=g.g().add(this.group);b.push(e);e=g.rect().addClass("highcharts-scrollbar-button").add(e);e.attr(e.crisp({x:-.5,y:-.5,width:c+1,height:c+1,r:d.buttonBorderRadius},e.strokeWidth()));g.path(l(["M",c/2+(a?-1:1),c/2-3,"L",c/2+(a?-1:1),c/2+3,"L",c/2+(a?2:-2),c/2],d.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a])},
setRange:function(a,b){var g=this.options,d=g.vertical,c=g.minWidth,e=this.barWidth,h,q=this.rendered&&!this.hasDragged?"animate":"attr";if(y(e)){a=Math.max(a,0);var r=Math.ceil(e*a);this.calculatedWidth=h=z(e*Math.min(b,1)-r);h<c&&(r=(e-c+h)*a,h=c);c=Math.floor(r+this.xOffset+this.yOffset);e=h/2-.5;this.from=a;this.to=b;d?(this.scrollbarGroup[q]({translateY:c}),this.scrollbar[q]({height:h}),this.scrollbarRifles[q]({translateY:e}),this.scrollbarTop=c,this.scrollbarLeft=0):(this.scrollbarGroup[q]({translateX:c}),
this.scrollbar[q]({width:h}),this.scrollbarRifles[q]({translateX:e}),this.scrollbarLeft=c,this.scrollbarTop=0);12>=h?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===g.showFull&&(0>=a&&1<=b?this.group.hide():this.group.show());this.rendered=!0}},initEvents:function(){var a=this;a.mouseMoveHandler=function(b){var g=a.chart.pointer.normalize(b),d=a.options.vertical?"chartY":"chartX",c=a.initPositions;!a.grabbedCenter||b.touches&&0===b.touches[0][d]||(g=a.cursorToScrollbarPosition(g)[d],
d=a[d],d=g-d,a.hasDragged=!0,a.updatePosition(c[0]+d,c[1]+d),a.hasDragged&&w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};a.mouseUpHandler=function(b){a.hasDragged&&w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=
!0};a.buttonToMinClick=function(b){var g=z(a.to-a.from)*a.options.step;a.updatePosition(z(a.from-g),z(a.to-g));w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=function(b){var g=(a.to-a.from)*a.options.step;a.updatePosition(a.from+g,a.to+g);w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var g=a.chart.pointer.normalize(b),d=a.to-a.from,c=a.y+a.scrollbarTop,e=a.x+a.scrollbarLeft;a.options.vertical&&g.chartY>c||!a.options.vertical&&
g.chartX>e?a.updatePosition(a.from+d,a.to+d):a.updatePosition(a.from-d,a.to-d);w(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=this.options;b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=z(1-z(b-a)),b=1);0>a&&(b=z(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();
this.init(this.chart.renderer,k(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,d=this.scrollbarGroup.element,l=this.mouseDownHandler,c=this.mouseMoveHandler,e=this.mouseUpHandler;a=[[b[a[0]].element,"click",this.buttonToMinClick],[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[d,"mousedown",l],[G,"mousemove",c],[G,"mouseup",e]];t&&a.push([d,"touchstart",l],[G,"touchmove",c],[G,"touchend",
e]);f(a,function(a){p.apply(null,a)});this._events=a},removeEvents:function(){f(this._events,function(a){d.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();f(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,H(a.scrollbarButtons))}};C(n.prototype,"init",function(a){var d=this;a.apply(d,Array.prototype.slice.call(arguments,
1));d.options.scrollbar&&d.options.scrollbar.enabled&&(d.options.scrollbar.vertical=!d.horiz,d.options.startOnTick=d.options.endOnTick=!1,d.scrollbar=new D(d.chart.renderer,d.options.scrollbar,d.chart),p(d.scrollbar,"changed",function(a){var g=Math.min(b(d.options.min,d.min),d.min,d.dataMin),c=Math.max(b(d.options.max,d.max),d.max,d.dataMax)-g;if(d.horiz&&!d.reversed||!d.horiz&&d.reversed){var e=g+c*this.to;g+=c*this.from}else e=g+c*(1-this.from),g+=c*(1-this.to);d.setExtremes(g,e,!0,!1,a)}))});C(n.prototype,
"render",function(a){var d=Math.min(b(this.options.min,this.min),this.min,this.dataMin),g=Math.max(b(this.options.max,this.max),this.max,this.dataMax),f=this.scrollbar,c=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(f){this.horiz?(f.position(this.left,this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:c+this.axisTitleMargin+this.offset),this.width,this.height),c=1):(f.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?
c+this.axisTitleMargin+this.offset:0),this.top,this.width,this.height),c=0);if(!this.opposite&&!this.horiz||this.opposite&&this.horiz)this.chart.scrollbarsOffsets[c]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(d)||isNaN(g)||!y(this.min)||!y(this.max)?f.setRange(0,0):(c=(this.min-d)/(g-d),d=(this.max-d)/(g-d),this.horiz&&!this.reversed||!this.horiz&&this.reversed?f.setRange(c,d):f.setRange(1-d,1-c))}});C(n.prototype,"getOffset",function(a){var b=this.horiz?2:1,d=this.scrollbar;a.apply(this,
Array.prototype.slice.call(arguments,1));d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=d.size+d.options.margin)});C(n.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,1))});a.Scrollbar=D})(J);(function(a){function D(a){this.init(a)}var p=a.addEvent,n=a.Axis,z=a.Chart,F=a.defaultOptions,y=a.defined,H=a.destroyObjectProperties,G=a.doc,f=a.each,w=a.erase,t=a.error,m=a.extend,k=a.grep,b=a.hasTouch,
d=a.isNumber,C=a.isObject,l=a.merge,I=a.pick,g=a.removeEvent,q=a.Scrollbar,u=a.Series,E=a.seriesTypes,c=a.wrap,e=a.swapXY,h=[].concat(a.defaultDataGroupingUnits),A=function(a){var r=k(arguments,d);if(r.length)return Math[a].apply(0,r)};h[4]=["day",[1,2,3,4]];h[5]=["week",[1,2,3]];m(F,{navigator:{height:40,margin:25,maskInside:!0,series:{type:void 0===E.areaspline?"line":"areaspline",compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:h},dataLabels:{enabled:!1,
zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},pointRange:0,shadow:!1,threshold:null},xAxis:{className:"highcharts-navigator-xaxis",tickLength:0,tickPixelInterval:200,labels:{align:"left",x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});D.prototype={drawHandle:function(a,c,
b,d){this.handles[c][d](b?{translateX:Math.round(this.left+this.height/2-8),translateY:Math.round(this.top+parseInt(a,10)+.5)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-8)})},getHandlePath:function(a){return e(["M",-4.5,.5,"L",3.5,.5,"L",3.5,15.5,"L",-4.5,15.5,"L",-4.5,.5,"M",-1.5,4,"L",-1.5,12,"M",.5,4,"L",.5,12],a)},drawOutline:function(a,c,b,d){var r=this.navigatorOptions.maskInside,e=this.outline.strokeWidth(),h=e/2;e=e%2/2;var x=this.outlineHeight,
v=this.scrollbarHeight,g=this.size,f=this.left-v,B=this.top;b?(f-=h,b=B+c+e,c=B+a+e,a=["M",f+x,B-v-e,"L",f+x,b,"L",f,b,"L",f,c,"L",f+x,c,"L",f+x,B+g+v].concat(r?["M",f+x,b-h,"L",f+x,c+h]:[])):(a+=f+v-e,c+=f+v-e,B+=h,a=["M",f,B,"L",a,B,"L",a,B+x,"L",c,B+x,"L",c,B,"L",f+g+2*v,B].concat(r?["M",a-h,B,"L",c+h,B]:[]));this.outline[d]({d:a})},drawMasks:function(a,c,b,e){var r=this.left,d=this.top,h=this.height;if(b){var x=[r,r,r];var v=[d,d+a,d+c];var g=[h,h,h];var B=[a,c-a,this.size-c]}else x=[r,r+a,r+
c],v=[d,d,d],g=[a,c-a,this.size-c],B=[h,h,h];f(this.shades,function(a,c){a[e]({x:x[c],y:v[c],width:g[c],height:B[c]})})},renderElements:function(){var a=this,c=a.navigatorOptions.maskInside,b=a.chart,d=b.inverted,h=b.renderer,e;a.navigatorGroup=e=h.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();f([!c,c,!c],function(c,b){a.shades[b]=h.rect().addClass("highcharts-navigator-mask"+(1===b?"-inside":"-outside")).add(e)});a.outline=h.path().addClass("highcharts-navigator-outline").add(e);f([0,
1],function(c){a.handles[c]=h.path(a.getHandlePath(d)).attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(e)})},update:function(a){this.destroy();l(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,c,b,h){var r=this.chart,e=this.scrollbarHeight,x,v=this.xAxis;var g=v.fake?r.xAxis[0]:v;var f=this.navigatorEnabled,B,l=this.rendered;var A=r.inverted;var k=r.xAxis[0].minRange;if(!this.hasDragged||y(b)){if(!d(a)||
!d(c))if(l)b=0,h=v.width;else return;this.left=I(v.left,r.plotLeft+e+(A?r.plotWidth:0));this.size=B=x=I(v.len,(A?r.plotHeight:r.plotWidth)-2*e);r=A?e:x+2*e;b=I(b,v.toPixels(a,!0));h=I(h,v.toPixels(c,!0));d(b)&&Infinity!==Math.abs(b)||(b=0,h=r);a=v.toValue(b,!0);c=v.toValue(h,!0);if(Math.abs(c-a)<k)if(this.grabbedLeft)b=v.toPixels(c-k,!0);else if(this.grabbedRight)h=v.toPixels(a+k,!0);else return;this.zoomedMax=Math.min(Math.max(b,h,0),B);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-
this.fixedWidth:Math.min(b,h),0),B);this.range=this.zoomedMax-this.zoomedMin;B=Math.round(this.zoomedMax);b=Math.round(this.zoomedMin);f&&(this.navigatorGroup.attr({visibility:"visible"}),l=l&&!this.hasDragged?"animate":"attr",this.drawMasks(b,B,A,l),this.drawOutline(b,B,A,l),this.drawHandle(b,0,A,l),this.drawHandle(B,1,A,l));this.scrollbar&&(A?(A=this.top-e,g=this.left-e+(f?0:(g.titleOffset||0)+g.axisTitleMargin),e=x+2*e):(A=this.top+(f?this.height:-e),g=this.left-e),this.scrollbar.position(g,A,
r,e),this.scrollbar.setRange(this.zoomedMin/x,this.zoomedMax/x));this.rendered=!0}},addMouseEvents:function(){var a=this,c=a.chart,e=c.container,h=[],d,g;a.mouseMoveHandler=d=function(c){a.onMouseMove(c)};a.mouseUpHandler=g=function(c){a.onMouseUp(c)};h=a.getPartsEvents("mousedown");h.push(p(e,"mousemove",d),p(G,"mouseup",g));b&&(h.push(p(e,"touchmove",d),p(G,"touchend",g)),h.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=h;a.series&&a.series[0]&&h.push(p(a.series[0].xAxis,"foundExtremes",
function(){c.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var c=this,b=[];f(["shades","handles"],function(r){f(c[r],function(h,e){b.push(p(h.element,a,function(a){c[r+"Mousedown"](a,e)}))})});return b},shadesMousedown:function(a,c){a=this.chart.pointer.normalize(a);var b=this.chart,r=this.xAxis,h=this.zoomedMin,e=this.left,d=this.size,x=this.range,g=a.chartX;b.inverted&&(g=a.chartY,e=this.top);if(1===c)this.grabbedCenter=g,this.fixedWidth=x,this.dragOffset=g-h;else{e=g-e-
x/2;if(0===c)e=Math.max(0,e);else if(2===c&&e+x>=d){e=d-x;var f=this.getUnionExtremes().dataMax}e!==h&&(this.fixedWidth=x,r=r.toFixedRange(e,e+x,null,f),b.xAxis[0].setExtremes(Math.min(r.min,r.max),Math.max(r.min,r.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(a,c){this.chart.pointer.normalize(a);var b=this.chart,r=b.xAxis[0],e=b.inverted&&!r.reversed||!b.inverted&&r.reversed;0===c?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=e?r.min:r.max):(this.grabbedRight=
!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=e?r.max:r.min);b.fixedRange=null},onMouseMove:function(a){var c=this,b=c.chart,r=c.left,e=c.navigatorSize,h=c.range,d=c.dragOffset,g=b.inverted;a.touches&&0===a.touches[0].pageX||(a=b.pointer.normalize(a),b=a.chartX,g&&(r=c.top,b=a.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,b-r,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,b-r)):c.grabbedCenter&&(c.hasDragged=!0,b<d?b=d:b>e+d-h&&(b=e+d-h),c.render(0,
0,b-d,b-d+h)),c.hasDragged&&c.scrollbar&&c.scrollbar.options.liveRedraw&&(a.DOMType=a.type,setTimeout(function(){c.onMouseUp(a)},0)))},onMouseUp:function(a){var c=this.chart,b=this.xAxis,e=this.scrollbar,r=a.DOMEvent||a;if(this.hasDragged&&(!e||!e.hasDragged)||"scrollbar"===a.trigger){if(this.zoomedMin===this.otherHandlePos)var h=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var d=this.fixedExtreme;this.zoomedMax===this.size&&(d=this.getUnionExtremes().dataMax);b=b.toFixedRange(this.zoomedMin,
this.zoomedMax,h,d);y(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:r})}"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(f(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},
removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&!1!==this.navigatorOptions.adaptToUpdatedData&&(f(a,function(a){g(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&g(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,e=b.navigator,h=e.enabled,d=b.scrollbar,r=d.enabled;b=h?e.height:0;var g=r?d.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=g;this.scrollbarEnabled=
r;this.navigatorEnabled=h;this.navigatorOptions=e;this.scrollbarOptions=d;this.outlineHeight=b+g;this.opposite=I(e.opposite,!h&&a.inverted);var f=this;d=f.baseSeries;r=a.xAxis.length;var k=a.yAxis.length,m=d&&d[0]&&d[0].xAxis||a.xAxis[0];a.extraMargin={type:f.opposite?"plotTop":"marginBottom",value:(h||!a.inverted?f.outlineHeight:0)+e.margin};a.inverted&&(a.extraMargin.type=f.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;f.navigatorEnabled?(f.xAxis=new n(a,l({breaks:m.options.breaks,ordinal:m.options.ordinal},
e.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:r,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[g,0,-g,0],width:b}:{offsets:[0,-g,0,g],height:b})),f.yAxis=new n(a,l(e.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||e.series.data?f.addBaseSeries():0===a.series.length&&c(a,"redraw",function(c,b){0<a.series.length&&!f.series&&
(f.setBaseSeries(),a.redraw=c);c.call(a,b)}),f.renderElements(),f.addMouseEvents()):f.xAxis={translate:function(c,b){var e=a.xAxis[0],h=e.getExtremes(),d=e.len-2*g,r=A("min",e.options.min,h.dataMin);e=A("max",e.options.max,h.dataMax)-r;return b?c*e/d+r:d*(c-r)/e},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:n.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=f.scrollbar=new q(a.renderer,l(a.options.scrollbar,{margin:f.navigatorEnabled?
0:10,vertical:a.inverted}),a),p(f.scrollbar,"changed",function(c){var b=f.size,e=b*this.to;b*=this.from;f.hasDragged=f.scrollbar.hasDragged;f.render(0,0,b,e);(a.options.scrollbar.liveRedraw||"mousemove"!==c.DOMType)&&setTimeout(function(){f.onMouseUp(c)})}));f.addBaseSeriesEvents();f.addChartEvents()},getUnionExtremes:function(a){var c=this.chart.xAxis[0],b=this.xAxis,e=b.options,h=c.options,d;a&&null===c.dataMin||(d={dataMin:I(e&&e.min,A("min",h.min,c.dataMin,b.dataMin,b.min)),dataMax:I(e&&e.max,
A("max",h.max,c.dataMax,b.dataMax,b.max))});return d},setBaseSeries:function(a){var c=this.chart;a=a||c.options&&c.options.navigator.baseSeries||0;this.series&&(this.removeBaseSeriesEvents(),f(this.series,function(a){a.destroy()}));var b=this.baseSeries=[];f(c.series||[],function(c,e){(c.options.showInNavigator||(e===a||c.options.id===a)&&!1!==c.options.showInNavigator)&&b.push(c)});this.xAxis&&!this.xAxis.fake&&this.addBaseSeries()},addBaseSeries:function(){var a=this,c=a.chart,b=a.series=[],e=a.baseSeries,
h,d=a.navigatorOptions.series,g,A={enableMouseTracking:!1,index:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0};if(e)f(e,function(e,r){A.name="Navigator "+(r+1);h=e.options||{};g=h.navigatorOptions||{};k=l(h,A,d,g);var f=g.data||d.data;a.hasNavigatorData=a.hasNavigatorData||!!f;k.data=f||h.data&&h.data.slice(0);e.navigatorSeries=c.initSeries(k);b.push(e.navigatorSeries)});else{var k=l(d,A);k.data=d.data;a.hasNavigatorData=
!!k.data;b.push(c.initSeries(k))}this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,c=a.baseSeries||[];c[0]&&c[0].xAxis&&p(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);!1!==this.navigatorOptions.adaptToUpdatedData&&f(c,function(c){c.xAxis&&p(c,"updatedData",this.updatedDataHandler);p(c,"remove",function(){this.navigatorSeries&&(w(a.series,this.navigatorSeries),this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=
this.xAxis,c;a.getExtremes&&(!(c=this.getUnionExtremes(!0))||c.dataMin===a.min&&c.dataMax===a.max||(a.min=c.dataMin,a.max=c.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,c=this.getExtremes(),b=c.dataMin,e=c.dataMax;c=c.max-c.min;var h=a.stickToMin,f=a.stickToMax,g=a.series&&a.series[0],A=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(h){var l=b;var k=l+c}f&&(k=e,h||(l=Math.max(k-c,g&&g.xData?g.xData[0]:-Number.MAX_VALUE)));A&&(h||
f)&&d(l)&&(this.min=this.userMin=l,this.max=this.userMax=k)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,c=this.navigatorSeries;a.stickToMin=d(this.xAxis.min)&&this.xAxis.min<=this.xData[0];a.stickToMax=Math.round(a.zoomedMax)>=Math.round(a.size);c&&!a.hasNavigatorData&&(c.options.pointStart=this.xData[0],c.setData(this.options.data,!1,null,!1))},addChartEvents:function(){p(this.chart,"redraw",function(){var a=this.navigator,c=a&&(a.baseSeries&&a.baseSeries[0]&&
a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);c&&a.render(c.min,c.max)})},destroy:function(){this.removeEvents();this.xAxis&&(w(this.chart.xAxis,this.xAxis),w(this.chart.axes,this.xAxis));this.yAxis&&(w(this.chart.yAxis,this.yAxis),w(this.chart.axes,this.yAxis));f(this.series||[],function(a){a.destroy&&a.destroy()});f("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),function(a){this[a]&&this[a].destroy&&this[a].destroy();
this[a]=null},this);f([this.handles],function(a){H(a)},this)}};a.Navigator=D;c(n.prototype,"zoom",function(a,c,b){var e=this.chart,h=e.options,d=h.chart.zoomType,f=h.navigator;h=h.rangeSelector;if(this.isXAxis&&(f&&f.enabled||h&&h.enabled))if("x"===d)e.resetZoomButton="blocked";else if("y"===d)var g=!1;else"xy"===d&&(e=this.previousZoom,y(c)?this.previousZoom=[this.min,this.max]:e&&(c=e[0],b=e[1],delete this.previousZoom));return void 0!==g?g:a.call(this,c,b)});c(z.prototype,"init",function(a,c,b){p(this,
"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new D(this)});a.call(this,c,b)});c(z.prototype,"setChartSize",function(a){var c=this.legend,b=this.navigator;a.apply(this,[].slice.call(arguments,1));if(b){var e=c.options;var h=b.xAxis;var d=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-
b.height-f-this.spacing[2]-("bottom"===e.verticalAlign&&e.enabled&&!e.floating?c.legendHeight+I(e.margin,10):0));h&&d&&(this.inverted?h.options.left=d.options.left=b.left:h.options.top=d.options.top=b.top,h.setAxisSize(),d.setAxisSize())}});c(u.prototype,"addPoint",function(a,c,b,e,h){var d=this.options.turboThreshold;d&&this.xData.length>d&&C(c,!0)&&this.chart.navigator&&t(20,!0);a.call(this,c,b,e,h)});c(z.prototype,"addSeries",function(a,c,b,e){a=a.call(this,c,!1,e);this.navigator&&this.navigator.setBaseSeries();
I(b,!0)&&this.redraw();return a});c(u.prototype,"update",function(a,c,b){a.call(this,c,!1);this.chart.navigator&&this.chart.navigator.setBaseSeries();I(b,!0)&&this.chart.redraw()});z.prototype.callbacks.push(function(a){var c=a.navigator;c&&(a=a.xAxis[0].getExtremes(),c.render(a.min,a.max))})})(J);(function(a){function D(a){this.init(a)}var p=a.addEvent,n=a.Axis,z=a.Chart,F=a.css,y=a.createElement,H=a.dateFormat,G=a.defaultOptions,f=G.global.useUTC,w=a.defined,t=a.destroyObjectProperties,m=a.discardElement,
k=a.each,b=a.extend,d=a.fireEvent,C=a.Date,l=a.isNumber,I=a.merge,g=a.pick,q=a.pInt,u=a.splat,E=a.wrap;b(G,{rangeSelector:{buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,zIndex:7},height:35,inputPosition:{align:"right"}}});G.lang=I(G.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});D.prototype={clickButton:function(a,b){var c=this,e=c.chart,d=c.buttonOptions[a],x=e.xAxis[0],v=e.scroller&&e.scroller.getUnionExtremes()||x||{},B=v.dataMin,m=v.dataMax,q=x&&Math.round(Math.min(x.max,
g(m,x.max))),t=d.type;v=d._range;var w,y=d.dataGrouping;if(null!==B&&null!==m){e.fixedRange=v;y&&(this.forcedDataGrouping=!0,n.prototype.setDataGrouping.call(x||{chart:this.chart},y,!1));if("month"===t||"year"===t)if(x){t={range:d,max:q,dataMin:B,dataMax:m};var z=x.minFromRange.call(t);l(t.newMax)&&(q=t.newMax)}else v=d;else if(v)z=Math.max(q-v,B),q=Math.min(z+v,m);else if("ytd"===t)if(x)void 0===m&&(B=Number.MAX_VALUE,m=Number.MIN_VALUE,k(e.series,function(a){a=a.xData;B=Math.min(a[0],B);m=Math.max(a[a.length-
1],m)}),b=!1),q=c.getYTDExtremes(m,B,f),z=w=q.min,q=q.max;else{p(e,"beforeRender",function(){c.clickButton(a)});return}else"all"===t&&x&&(z=B,q=m);c.setSelected(a);if(x)x.setExtremes(z,q,g(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d});else{var K=u(e.options.xAxis)[0];var C=K.range;K.range=v;var D=K.min;K.min=w;p(e,"load",function(){K.range=C;K.min=D})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",
count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,b=a.options.rangeSelector,f=b.buttons||[].concat(c.defaultButtons),g=b.selected,l=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&d(a,"blur");b&&b.blur&&d(b,"blur")};c.chart=a;c.options=b;c.buttons=[];a.extraTopMargin=b.height;c.buttonOptions=f;this.unMouseDown=p(a.container,"mousedown",l);this.unResize=p(a,"resize",l);k(f,c.computeButtonRange);
void 0!==g&&f[g]&&this.clickButton(g,!1);p(a,"load",function(){p(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,b=a.xAxis[0],d=Math.round(b.max-b.min),g=!b.hasVisibleSeries;a=a.scroller&&a.scroller.getUnionExtremes()||b;var r=a.dataMin,x=a.dataMax;a=this.getYTDExtremes(x,r,f);var v=a.min,n=a.max,m=this.selected,
p=l(m),q=this.options.allButtonsEnabled,t=this.buttons;k(this.buttonOptions,function(a,c){var e=a._range,h=a.type,f=a.count||1,l=t[c],k=0;var A=c===m;var B=e>x-r,w=e<b.minRange,u=!1,y=!1;e=e===d;("month"===h||"year"===h)&&d>=864E5*{month:28,year:365}[h]*f&&d<=864E5*{month:31,year:366}[h]*f?e=!0:"ytd"===h?(e=n-v===d,u=!A):"all"===h&&(e=b.max-b.min>=x-r,y=!A&&p&&e);h=!q&&(B||w||y||g);A=A&&e||e&&!p&&!u;h?k=3:A&&(p=!0,k=2);l.state!==k&&l.setState(k)})},computeButtonRange:function(a){var b=a.type,c=a.count||
1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*c;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*c},setInputValue:function(a,b){var c=this.chart.options.rangeSelector,e=this[a+"Input"];w(b)&&(e.previousValue=e.HCTime,e.HCTime=b);e.value=H(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:H(c.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];F(this[a+
"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){F(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=m.value,b=(k.inputDateParser||Date.parse)(a),e=d.xAxis[0],h=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:e,g=h.dataMin;h=h.dataMax;b!==m.previousValue&&(m.previousValue=b,l(b)||(b=a.split("-"),b=Date.UTC(q(b[0]),q(b[1])-1,q(b[2]))),
l(b)&&(f||(b+=6E4*(new Date).getTimezoneOffset()),n?b>c.maxInput.HCTime?b=void 0:b<g&&(b=g):b<c.minInput.HCTime?b=void 0:b>h&&(b=h),void 0!==b&&e.setExtremes(n?b:e.min,n?e.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var c=this,d=c.chart,g=d.renderer,k=d.options.rangeSelector,v=c.div,n="min"===a,m,p,t=this.inputGroup;this[a+"Label"]=p=g.label(G.lang[n?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);t.offset+=p.width+
5;this[a+"DateBox"]=g=g.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:k.inputBoxWidth||90,height:k.inputBoxHeight||17,stroke:k.inputBoxBorderColor||"#cccccc","stroke-width":1,"text-align":"center"}).on("click",function(){c.showInput(a);c[a+"Input"].focus()}).add(t);t.offset+=g.width+(n?10:0);this[a+"Input"]=m=y("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},v);m.onfocus=function(){c.showInput(a)};m.onblur=function(){c.hideInput(a)};
m.onchange=b;m.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector;a=g((b.buttonPosition||{}).y,a.plotTop-a.axisOffset[0]-b.height);return{buttonTop:a,inputTop:a-10}},getYTDExtremes:function(a,b,d){var c=new C(a),e=c[C.hcGetFullYear]();d=d?C.UTC(e,0,1):+new C(e,0,1);b=Math.max(b||0,d);c=c.getTime();return{max:Math.min(a||c,c),min:b}},render:function(a,e){var c=this,d=c.chart,f=d.renderer,l=d.container,v=d.options,n=v.exporting&&!1!==v.exporting.enabled&&
v.navigation&&v.navigation.buttonOptions,m=v.rangeSelector,p=c.buttons;v=G.lang;var q=c.div;q=c.inputGroup;var t=m.buttonTheme,u=m.buttonPosition||{},z=m.inputEnabled,C=t&&t.states,D=d.plotLeft,F=this.getPosition(),E=c.group,H=c.rendered;if(!1!==m.enabled){if(!H){c.group=E=f.g("range-selector-buttons").add();c.zoomText=f.text(v.rangeSelectorZoom,g(u.x,D),15).css(m.labelStyle).add(E);var I=g(u.x,D)+c.zoomText.getBBox().width+5;k(c.buttonOptions,function(a,b){p[b]=f.button(a.text,I,0,function(){c.clickButton(b);
c.isActive=!0},t,C&&C.hover,C&&C.select,C&&C.disabled).attr({"text-align":"center"}).add(E);I+=p[b].width+g(m.buttonSpacing,5)});!1!==z&&(c.div=q=y("div",null,{position:"relative",height:0,zIndex:1}),l.parentNode.insertBefore(q,l),c.inputGroup=q=f.g("input-group").add(),q.offset=0,c.drawInput("min"),c.drawInput("max"))}c.updateButtonStates();E[H?"animate":"attr"]({translateY:F.buttonTop});!1!==z&&(q.align(b({y:F.inputTop,width:q.offset,x:n&&F.inputTop<(n.y||0)+n.height-d.spacing[0]?-40:0},m.inputPosition),
!0,d.spacingBox),w(z)||(d=E.getBBox(),q[q.alignAttr.translateX<d.x+d.width+10?"hide":"show"]()),c.setInputValue("min",a),c.setInputValue("max",e));c.rendered=!0}},update:function(a){var b=this.chart;I(!0,b.options.rangeSelector,a);this.destroy();this.init(b)},destroy:function(){var b=this,d=b.minInput,h=b.maxInput;b.unMouseDown();b.unResize();t(b.buttons);d&&(d.onfocus=d.onblur=d.onchange=null);h&&(h.onfocus=h.onblur=h.onchange=null);a.objectEach(b,function(a,c){a&&"chart"!==c&&(a.destroy?a.destroy():
a.nodeType&&m(this[c]));a!==D.prototype[c]&&(b[c]=null)},this)}};n.prototype.toFixedRange=function(a,b,d,f){var c=this.chart&&this.chart.fixedRange;a=g(d,this.translate(a,!0,!this.horiz));b=g(f,this.translate(b,!0,!this.horiz));d=c&&(b-a)/c;.7<d&&1.3>d&&(f?a=b-c:b=a+c);l(a)||(a=b=void 0);return{min:a,max:b}};n.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],d=this.max,f=function(a,c){var d=new Date(a),e=d["get"+b]();d["set"+b](e+c);e===d["get"+b]()&&d.setDate(0);
return d.getTime()-a};if(l(a)){var k=d-a;var m=a}else k=d+f(d,-a.count),this.chart&&(this.chart.fixedRange=d-k);var v=g(this.dataMin,Number.MIN_VALUE);l(k)||(k=v);k<=v&&(k=v,void 0===m&&(m=f(k,a.count)),this.newMax=Math.min(k+m,this.dataMax));l(d)||(k=void 0);return k};E(z.prototype,"init",function(a,b,d){p(this,"init",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new D(this))});a.call(this,b,d)});z.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();
l(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector;if(d){var f=p(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var g=p(a,"redraw",b);b()}p(a,"destroy",function(){d&&(g(),f())})});a.RangeSelector=D})(J);(function(a){var D=a.arrayMax,p=a.arrayMin,n=a.Axis,z=a.Chart,F=a.defined,y=a.each,H=a.format,G=a.grep,f=a.inArray,w=a.isNumber,t=a.isString,m=a.map,k=a.merge,b=a.pick,d=a.Point,C=a.Series,l=a.splat,I=a.SVGRenderer,g=a.wrap,q=C.prototype,u=q.init,E=q.processData,c=d.prototype.tooltipFormatter;
a.StockChart=a.stockChart=function(c,d,f){var e=t(c)||c.nodeName,h=arguments[e?1:0],g=h.series,n=a.getOptions(),p,q=b(h.navigator&&h.navigator.enabled,n.navigator.enabled,!0),A=q?{startOnTick:!1,endOnTick:!1}:null,u={marker:{enabled:!1,radius:2}},w={shadow:!1,borderWidth:0};h.xAxis=m(l(h.xAxis||{}),function(a){return k({minPadding:0,maxPadding:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},n.xAxis,a,{type:"datetime",categories:null},A)});h.yAxis=m(l(h.yAxis||{}),function(a){p=
b(a.opposite,!0);return k({labels:{y:-2},opposite:p,showLastLabel:!1,title:{text:null}},n.yAxis,a)});h.series=null;h=k({chart:{panning:!0,pinchType:"x"},navigator:{enabled:q},scrollbar:{enabled:b(n.scrollbar.enabled,!0)},rangeSelector:{enabled:b(n.rangeSelector.enabled,!0)},title:{text:null},tooltip:{shared:!0,crosshairs:!0},legend:{enabled:!1},plotOptions:{line:u,spline:u,area:u,areaspline:u,arearange:u,areasplinerange:u,column:w,columnrange:w,candlestick:w,ohlc:w}},h,{isStock:!0});h.series=g;return e?
new z(c,h,f):new z(h,d)};g(n.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var d=this.options.labels;return this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.call(this,[].slice.call(arguments,1))});g(n.prototype,"destroy",function(a){var b=this.chart,c=this.options&&this.options.top+","+this.options.height;c&&b._labelPanes&&b._labelPanes[c]===
this&&delete b._labelPanes[c];return a.call(this,Array.prototype.slice.call(arguments,1))});g(n.prototype,"getPlotLinePath",function(c,d,g,k,l,n){var e=this,h=this.isLinked&&!this.series?this.linkedParent.series:this.series,r=e.chart,p=r.renderer,v=e.left,q=e.top,x,u,A,z,C=[],D=[];if("colorAxis"===e.coll)return c.apply(this,[].slice.call(arguments,1));D=function(a){var b="xAxis"===a?"yAxis":"xAxis";a=e.options[b];return w(a)?[r[b][a]]:t(a)?[r.get(a)]:m(h,function(a){return a[b]})}(e.coll);y(e.isXAxis?
r.yAxis:r.xAxis,function(a){if(F(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=F(a.options[b])?r[b][a.options[b]]:r[b][0];e===b&&D.push(a)}});var E=D.length?[]:[e.isXAxis?r.yAxis[0]:r.xAxis[0]];y(D,function(b){-1!==f(b,E)||a.find(E,function(a){return a.pos===b.pos&&a.len&&b.len})||E.push(b)});var G=b(n,e.translate(d,null,null,k));w(G)&&(e.horiz?y(E,function(a){var b;u=a.pos;z=u+a.len;x=A=Math.round(G+e.transB);if(x<v||x>v+e.width)l?x=A=Math.min(Math.max(v,
x),v+e.width):b=!0;b||C.push("M",x,u,"L",A,z)}):y(E,function(a){var b;x=a.pos;A=x+a.len;u=z=Math.round(q+e.height-G);if(u<q||u>q+e.height)l?u=z=Math.min(Math.max(q,u),e.top+e.height):b=!0;b||C.push("M",x,u,"L",A,z)}));return 0<C.length?p.crispPolyLine(C,g||1):null});n.prototype.getPlotBandPath=function(a,b){var c=this.getPlotLinePath(b,null,null,!0),d=this.getPlotLinePath(a,null,null,!0),e=[],h;if(d&&c)if(d.toString()===c.toString())e=d,e.isFlat=!0;else for(h=0;h<d.length;h+=6)e.push("M",d[h+1],d[h+
2],"L",d[h+4],d[h+5],c[h+4],c[h+5],c[h+1],c[h+2],"z");else e=null;return e};I.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};g(n.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});g(n.prototype,"drawCrosshair",function(a,c,d){var e,f;a.call(this,c,d);if(F(this.crosshair.label)&&this.crosshair.label.enabled&&
this.cross){a=this.chart;var g=this.options.crosshair.label,h=this.horiz,k=this.opposite,l=this.left,n=this.top,m=this.crossLabel,p=g.format,q="",t="inside"===this.options.tickPosition,u=!1!==this.crosshair.snap,w=0;c||(c=this.cross&&this.cross.e);var y=h?"center":k?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";m||(m=this.crossLabel=a.renderer.label(null,null,null,g.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:g.align||
y,padding:b(g.padding,8),r:b(g.borderRadius,3),zIndex:2}).add(this.labelGroup));h?(y=u?d.plotX+l:c.chartX,n+=k?0:this.height):(y=k?this.width+l:0,n=u?d.plotY+n:c.chartY);p||g.formatter||(this.isDatetimeAxis&&(q="%b %d, %Y"),p="{value"+(q?":"+q:"")+"}");c=u?d[this.isXAxis?"x":"y"]:this.toValue(h?c.chartX:c.chartY);m.attr({text:p?H(p,{value:c}):g.formatter.call(this,c),x:y,y:n,visibility:"visible"});c=m.getBBox();if(h){if(t&&!k||!t&&k)n=m.y-c.height}else n=m.y-c.height/2;h?(e=l-c.x,f=l+this.width-c.x):
(e="left"===this.labelAlign?l:0,f="right"===this.labelAlign?l+this.width:a.chartWidth);m.translateX<e&&(w=e-m.translateX);m.translateX+c.width>=f&&(w=-(m.translateX+c.width-f));m.attr({x:y+w,y:n,anchorX:h?y:this.opposite?0:a.chartWidth,anchorY:h?this.opposite?a.chartHeight:0:n+c.height/2})}});q.init=function(){u.apply(this,arguments);this.setCompare(this.options.compare)};q.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==
d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};q.processData=function(){var a,b=-1;E.apply(this,arguments);if(this.xAxis&&this.processedYData){var c=this.processedXData;var d=this.processedYData;var g=d.length;this.pointArrayMap&&(b=f("close",this.pointArrayMap),-1===b&&(b=f(this.pointValKey||"y",this.pointArrayMap)));for(a=0;a<g-1;a++){var k=d[a]&&-1<b?d[a][b]:d[a];if(w(k)&&c[a+
1]>=this.xAxis.min&&0!==k){this.compareValue=k;break}}}};g(q,"getExtremes",function(a){a.apply(this,[].slice.call(arguments,1));if(this.modifyValue){var b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=p(b);this.dataMax=D(b)}});n.prototype.setCompare=function(a,c){this.isXAxis||(y(this.series,function(b){b.setCompare(a)}),b(c,!0)&&this.chart.redraw())};d.prototype.tooltipFormatter=function(d){d=d.replace("{point.change}",(0<this.change?"+":"")+a.numberFormat(this.change,
b(this.series.tooltipOptions.changeDecimals,2)));return c.apply(this,[d])};g(C.prototype,"render",function(a){this.chart.is3d&&this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(!this.clipBox&&this.animate?(this.clipBox=k(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:this.yAxis.len}):this.clipBox&&(this.clipBox.width=this.xAxis.len,this.clipBox.height=
this.yAxis.len));a.call(this)});g(z.prototype,"getSelectedPoints",function(a){var b=a.call(this);y(this.series,function(a){a.hasGroupedData&&(b=b.concat(G(a.points||[],function(a){return a.selected})))});return b});g(z.prototype,"update",function(a,b){"scrollbar"in b&&this.navigator&&(k(!0,this.options.scrollbar,b.scrollbar),this.navigator.update({},!1),delete b.scrollbar);return a.apply(this,Array.prototype.slice.call(arguments,1))})})(J)});